### ISSUE TITLE
[Bug]: Strange error log during merge run

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11174] opened 2023-08-11 09:17 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 951818f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Found many strange logs during merge run, as

http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-11164%5C%22%7D%20%7C%3D%20%60txn_database%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D

<img width="1851" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/3c162194-942d-496e-b3cc-bd662408bcd3">

### Expected Behavior

If the logs occurred are expected, the cause of the error should be provided. If not, it's necessary to find the root cause and fix it.

**Comment by XuPeng-SH** [comment] 2023-08-12 01:31
assign to @w-zr

**Comment by w-zr** [comment] 2023-11-17 11:20
the logs are as expected, the root cause is these tables are not exist in database.

**Closed as completed** 2023-11-27 13:09 UTC
Labels: kind/bug, severity/s1
