### ISSUE TITLE
[Bug]:  mo-service failed to restart in standalone mode

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#10317] opened 2023-06-29 09:11 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): cd7cea6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

failed to restart, continue to print the following error logs:
<img width="1190" alt="企业微信截图_639a68bd-401e-4623-a5ba-0e35d27d9cfc" src="https://github.com/matrixorigin/matrixone/assets/77312370/7fd5e3dd-43ff-4221-a294-765562b215af">

and another problem is that untimely checkpointing has resulted in a large amount of data in the log service, @XuPeng-SH please take a look at this, thank you.

<img width="547" alt="企业微信截图_4790d34b-f5a1-4359-824f-d4a98b2ee697" src="https://github.com/matrixorigin/matrixone/assets/77312370/858f5ab2-2522-4e4d-9a91-2c1b63c3dcd5">

**Comment by XuPeng-SH** [comment] 2023-06-29 09:17
@aptend please help to investigate this issue

**Comment by aptend** [comment] 2023-06-29 10:23
the last checkpoint happened at `2023/06/07 23:37:44.190314 +0800 INFO checkpoint/runner.go:388 CKP[I][2](1686151899171596338-1->1686152119171129973-0) is done, takes 17.937341ms, truncate 29515`, for the rest of 22 days, no checkpoints anymore.

The checkpoint-stopping problem has been fixed in https://github.com/matrixorigin/matrixone/pull/10174, which is merged on 2023/6/24 while the version in the issue is 2023/6/7

**Comment by volgariver6** [comment] 2023-06-30 02:19
这个问题修复之后，在启动的过程中发生OOM，抓了一下heap：

<img width="1275" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/f25dc67b-b433-4e5b-a639-81101923f33d">

**Comment by volgariver6** [comment] 2023-06-30 03:52
![pprof001](https://github.com/matrixorigin/matrixone/assets/18366608/95097d5b-8f72-4c1f-b14c-0642263ebcc9)

**Comment by volgariver6** [comment] 2023-06-30 07:36
context超时问题导致的无限循环问题已经修复 #10328 ，但是现在集群还有一个问题，40G 日志数据，在回放时会OOM，相关信息已经上传。请 @jiangxinmeng1 看一下。

**Comment by LeftHandCold** [comment] 2023-06-30 08:46
> context超时问题导致的无限循环问题已经修复 #10328 ，但是现在集群还有一个问题，40G 日志数据，在回放时会OOM，相关信息已经上传。请 @jiangxinmeng1 看一下。

这种问题不就是因为 https://github.com/matrixorigin/matrixone/pull/10174 修复前的bug导致的40G数据嘛？这个fix只是不会再生成40G数据了而已，不再发生这种情况了，你之前产生的没用啊。 @volgariver6

**Comment by volgariver6** [comment] 2023-07-03 03:30
已经创建issue跟踪解决hakeeper snapshot的问题

**Comment by sukki37** [comment] 2023-07-07 15:16
waiting for #10336 and #10338

**Comment by sukki37** [comment] 2023-07-15 15:38
still waiting for https://github.com/matrixorigin/matrixone/issues/10336 and https://github.com/matrixorigin/matrixone/issues/10338 @aressu1985 please follow the progress

**Comment by aressu1985** [comment] 2023-07-22 13:23
in tracking

**Comment by aressu1985** [comment] 2023-08-02 12:52
not working on it

**Comment by heni02** [comment] 2023-08-10 07:53
load long time data and after stop mo ,then restart succeed
<img width="883" alt="企业微信截图_34dca64e-742f-4d96-a2d9-8d03ff2cedda" src="https://github.com/matrixorigin/matrixone/assets/113406637/fae1916d-3ca3-4322-8795-0833ce5af02a">
and  log service data is not so large
<img width="447" alt="企业微信截图_e222fe83-1514-4b25-a5e1-a15c6d51083f" src="https://github.com/matrixorigin/matrixone/assets/113406637/f58cc461-c4ad-43d9-b994-be32ed0ca2e6">

so confirm closed
commit id:8af14455f059e657890f4249ca63699476bb7f63

**Comment by aressu1985** [comment] 2023-08-12 02:37
fixed

**Closed by aressu1985** 2023-08-12 02:37 UTC
Labels: kind/bug, needs-triage, severity/s1
