### ISSUE TITLE
[Bug]: PROD环境，对订阅库表执行增加联合主键操作报错[21S01][1136] Column count doesn't match value count at row 1

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#14846] opened 2024-03-08 02:51 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.1.1

### Commit ID

9d616832a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

alter table mo_sample_data_tpch_sf10.partsupp add PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY);
alter table mo_sample_data_tpch_sf10.LINEITEM add PRIMARY KEY (L_ORDERKEY, L_LINENUMBER);
alter table mo_sample_data_tpch_sf1.partsupp add PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY);
alter table mo_sample_data_tpch_sf1.LINEITEM add PRIMARY KEY (L_ORDERKEY, L_LINENUMBER);
报错
[21S01][1136] Column count doesn't match value count at row 1

### Expected Behavior

正常添加联合主键

### Steps to Reproduce

```Markdown
如上
```

**Comment by xiaoshuwei** [comment] 2024-03-11 03:52
目前dump用户创建有联合主键的表也会报相同的错误
```
CREATE TABLE mo_sample_data_tpch_sf_abc.`lineitem` (
                                                       `l_orderkey` BIGINT NOT NULL,
                                                       `l_linenumber` INT NOT NULL,
                                                       PRIMARY KEY (`L_ORDERKEY`, `L_LINENUMBER`)
);
```
<img width="959" alt="image" src="https://github.com/matrixorigin/matrixone/assets/130344965/af1616c8-80c6-473b-80cc-000c2ed059f1">

**Comment by LiSong0214** [comment] 2024-03-11 06:20
我也试了下，在 MO Cloud 生产环境（即 MO v1.1.1）的普通租户下，是可以执行：1）对一个没有主键的表添加联合主键；2）创建一张带有联合主键的表。从现象上看，sys 租户创建不了（或者说 dump/root用户创建不了），这很奇怪，我们居然有逻辑区分了它们的语法支持。

**Comment by qingxinhome** [comment] 2024-03-15 02:00
The upgrade of the mo_indexes table under the system tenant failed during version update。

**Comment by arjunsk** [comment] 2024-03-15 03:29
Upgrade error logs: https://grafana.cn-qa.matrixone.tech/explore?panes=%7B%226B2%22:%7B%22datasource%22:%22d28a3d73-a58a-4bd1-95bd-4ad0f7be2a4a%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixorigin_io_owner%3D%5C%22freetier-02%5C%22%7D%20%7C%3D%20%60Upgrade%20failed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22d28a3d73-a58a-4bd1-95bd-4ad0f7be2a4a%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706774400000%22,%22to%22:%221707292799000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by arjunsk** [comment] 2024-03-15 03:33
[Explore-logs-2024-03-14 20_33_37.txt](https://github.com/matrixorigin/matrixone/files/14610397/Explore-logs-2024-03-14.20_33_37.txt)

**Comment by arjunsk** [comment] 2024-03-15 03:57
```sql
mysql> SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA ="mo_catalog" AND TABLE_NAME ="mo_indexes" AND COLUMN_NAME = "algo";
+-------------+
| column_name |
+-------------+
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
| algo        |
+-------------+
34 rows in set (0.35 sec)

mysql> mysql> SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA ="mo_catalog" AND TABLE_NAME ="mo_indexes";
+------------------+
| column_name      |
+------------------+
| __mo_cpkey_col   |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| __mo_cpkey_col   |
| algo             |
| algo_params      |
| algo_table_type  |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
+------------------+
557 rows in set (0.41 sec)

```

**Comment by arjunsk** [comment] 2024-03-15 04:07
```sql
mysql> SELECT distinct(COLUMN_NAME) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA ="mo_catalog" AND TABLE_NAME ="mo_indexes";
+------------------+
| column_name      |
+------------------+
| __mo_cpkey_col   |
| column_name      |
| comment          |
| database_id      |
| hidden           |
| id               |
| index_table_name |
| is_visible       |
| name             |
| options          |
| ordinal_position |
| table_id         |
| type             |
| algo             | <-------[showing this column is present]
| algo_params      | <-------[showing this column is present]
| algo_table_type  | <-------[showing this column is present]
+------------------+
16 rows in set (0.34 sec)

```

However there are quite alot of duplicates

```sql
mysql> SELECT COLUMN_NAME, COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA ="mo_catalog" AND TABLE_NAME ="mo_indexes" GROUP BY COLUMN_NAME;
+------------------+----------+
| column_name      | count(*) |
+------------------+----------+
| __mo_cpkey_col   |       35 |
| column_name      |       35 |
| comment          |       35 |
| database_id      |       35 |
| hidden           |       35 |
| id               |       35 |
| index_table_name |       35 |
| is_visible       |       35 |
| name             |       35 |
| options          |       35 |
| ordinal_position |       35 |
| table_id         |       35 |
| type             |       35 |
| algo             |       34 |
| algo_params      |       34 |
| algo_table_type  |       34 |
+------------------+----------+
```

**Comment by arjunsk** [comment] 2024-03-17 23:14
PR raised and merged to 1.1-dev. waiting for the Cluster update.

**Comment by qingxinhome** [comment] 2024-03-18 07:36
The issue has been submitted to PR, please verify and test it @tianyahui-python @daviszhen @LiSong0214

**Comment by tianyahui-python** [comment] 2024-03-18 07:37
等待升级到qa 验证。。。

**Comment by arjunsk** [comment] 2024-03-18 17:22
The issue is fixed in 1.1-dev branch.

```sql 
mysql> select git_version();
+---------------+
| git_version() |
+---------------+
| afb4934ae     |
+---------------+
1 row in set (0.18 sec)

mysql> mysql> desc mo_catalog.mo_;
+------------------+---------------------+------+------+---------+-------+---------+
| Field            | Type                | Null | Key  | Default | Extra | Comment |
+------------------+---------------------+------+------+---------+-------+---------+
| id               | BIGINT UNSIGNED(64) | NO   | PRI  | NULL    |       |         |
| table_id         | BIGINT UNSIGNED(64) | NO   |      | NULL    |       |         |
| database_id      | BIGINT UNSIGNED(64) | NO   |      | NULL    |       |         |
| name             | VARCHAR(64)         | NO   |      | NULL    |       |         |
| type             | VARCHAR(11)         | NO   |      | NULL    |       |         |
| algo             | VARCHAR(11)         | YES  |      | NULL    |       |         |
| algo_table_type  | VARCHAR(11)         | YES  |      | NULL    |       |         |
| algo_params      | VARCHAR(2048)       | YES  |      | NULL    |       |         |
| is_visible       | TINYINT(8)          | NO   |      | NULL    |       |         |
| hidden           | TINYINT(8)          | NO   |      | NULL    |       |         |
| comment          | VARCHAR(2048)       | NO   |      | NULL    |       |         |
| column_name      | VARCHAR(256)        | NO   | PRI  | NULL    |       |         |
| ordinal_position | INT UNSIGNED(32)    | NO   |      | NULL    |       |         |
| options          | TEXT(0)             | YES  |      | NULL    |       |         |
| index_table_name | VARCHAR(5000)       | YES  |      | NULL    |       |         |
+------------------+---------------------+------+------+---------+-------+---------+
15 rows in set (0.50 sec)

mysql> SELECT COLUMN_NAME, COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA ="mo_catalog" AND TABLE_NAME ="mo_indexes" GROUP BY COLUMN_NAME;
+------------------+----------+
| column_name      | count(*) |
+------------------+----------+
| __mo_cpkey_col   |       36 |
| algo             |       36 |
| algo_params      |       36 |
| algo_table_type  |       36 |
| column_name      |       36 |
| comment          |       36 |
| database_id      |       36 |
| hidden           |       36 |
| id               |       36 |
| index_table_name |       36 |
| is_visible       |       36 |
| name             |       36 |
| options          |       36 |
| ordinal_position |       36 |
| table_id         |       36 |
| type             |       36 |
+------------------+----------+
16 rows in set (0.36 sec)

mysql> 



```

**Comment by tianyahui-python** [comment] 2024-04-01 10:10
fixed

**Comment by tianyahui-python** [comment] 2024-04-02 10:10
fixed

**Closed** 2024-04-07 03:02 UTC
Labels: kind/bug, severity/s-1, impact/1.1, resolved/v1.1.2
