### ISSUE TITLE
[Bug]: accidental bvt error for IS NOT operator

### ISSUE THREAD

**Issue by yingfeng** [matrixorigin/matrixone#6249] opened 2022-11-03 16:34 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):4c092b71365f1d8c5118484f51e4615f5e59207f
- Hardware parameters:
- OS type:
- Others:


Both configuration of tae-logservice and cn-tae-dn-tae
```

### Actual Behavior

<img width="1067" alt="截屏2022-11-04 00 30 46" src="https://user-images.githubusercontent.com/7248/199778793-52917109-a36d-4dcb-b21a-c27909c7f37e.png">

### Steps to Reproduce

```Markdown
Data ingest:


CREATE TABLE t1(
id INT PRIMARY KEY,
name VARCHAR(20),
class VARCHAR(4)
);
CREATE TABLE t2(
id INT,
nation VARCHAR(20),
major VARCHAR(20)
);
INSERT INTO t1 VALUES('1001', 'JACK', '');
INSERT INTO t1 VALUES('1002', 'TOM', '0');
INSERT INTO t1 VALUES('1003', '1', '5');
INSERT INTO t1 VALUES('1004', ' ', '9');
INSERT INTO t2 VALUES('1001', 'BRAZIL', 'AI');
INSERT INTO t2 VALUES('1002', 'IRELAND', '1');
INSERT INTO t2 VALUES('1003', 'TRUE', 'AI');
INSERT INTO t2 VALUES('1004', 'IRELAND', '0');
```

Query:

```
SELECT t1.id, t1.name, t2.nation FROM t1 INNER JOIN t2 ON t1.id = t2.id WHERE t1.class IS NOT FALSE AND t2.major IS NOT TRUE;
```

Repeated execution on the query will have different results
```

**Comment by badboynt1** [comment] 2022-11-04 02:43
there are mutiple predicates,  executed in an random order and lead to different results.

according to @fengttt , this is not a bug. All database behave this way.   No gurantee of execution ordering, actually no guanrantee of a predicate is evaluated at all.

but i will check it and make sure bvt can run through

**Comment by yingfeng** [comment] 2022-11-04 02:52
just make bvt pass

**Comment by badboynt1** [comment] 2022-11-04 09:25
new pr has been merged. bvt works fine now

**Closed** 2022-11-04 09:26 UTC
Labels: kind/bug, severity/s1
