### ISSUE TITLE
[Bug]: BVT Panic

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#8536] opened 2023-03-20 03:28 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): main
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/2995754/226239778-3c386858-6a2e-4523-9c25-6fc8cf7cf261.png)

**Comment by nnsgmsone** [comment] 2023-03-20 07:49
xupeng please take a look

**Comment by nnsgmsone** [comment] 2023-03-20 08:35
At the moment it looks like this will block the pr merge.

**Comment by triump2020** [comment] 2023-03-20 11:29
Cause :   maybe sb introduced new types in pkg/types/type.go,  but don't  handle them  in `CompareGeneric(...)`.
![1679311697920](https://user-images.githubusercontent.com/63033222/226326745-418be868-555b-4a55-bff4-9ba8f82db287.png)

**Comment by aunjgr** [comment] 2023-03-20 17:44
@badboynt1 I believe it's caused by #8398

**Comment by triump2020** [comment] 2023-03-21 03:06
@matrix-meow rerun failed

**Comment by fengttt** [comment] 2023-03-21 16:28
This is not over yet.   Two big questions,

1. T_any should not be used in compare.   So the assert was correct.   Someone needs to fix the root cause.
2. How did the bug get checked in?    Flaky?

**Comment by fengttt** [comment] 2023-03-21 16:36
@triump2020 while the fix will work, I think CompareGeneric itself is a mistake.    
1. It is slow, we typeswitch every call.     This problem is not specific to this function but, spreads through our code.
2. any time someone added a new type, this code needs to change.    Therefore, this code really belongs to container/type package, not TAE.   

So this is a refactor task.

**Comment by XuPeng-SH** [comment] 2023-03-21 16:49
> 
CompareGeneric was implemented before go generic is introduced. It is slow. Yes, we need a generic compare function in container/type package to replace all similar functions.

**Closed** 2023-03-25 09:40 UTC
Labels: kind/bug, needs-triage, severity/s-1
