### ISSUE TITLE
[Bug]: morpc wait the message for 24 minutes

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#12911] opened 2023-11-23 02:19 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

free01 yesterday
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/9932563f-2668-4b73-b469-6f1af4fb6d6b)

![企业微信截图_33fb10a9-6477-47c0-8236-168a0d88a854](https://github.com/matrixorigin/matrixone/assets/60595215/8a2241e8-c7ca-492b-882f-89a0cbb248ce)

### Expected Behavior

no waiting so long

### Steps to Reproduce

```Markdown
free01

i am not sure we can reproduce it.
```

**Comment by daviszhen** [comment] 2023-11-23 02:19
#11966

**Comment by daviszhen** [comment] 2023-11-23 02:20
导致事务泄漏

http://47.97.80.230/explore?orgId=1&panes=%7B%22aG4%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22freetier-01%5C%22%7D%20%7C%3D%20%60goroutine%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221700639678785%22,%22to%22:%221700639679785%22%7D%7D,%22Kx9%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22,apps_kruise_io_cloneset_instance_id%3D%5C%225vzng%5C%22,container%3D%5C%22main%5C%22,controller_revision_hash%3D%5C%22default-cn-96868c55b%5C%22,filename%3D%5C%22%2Fvar%2Flog%2Fpods%2Ffreetier-01_default-cn-5vzng_c8e99ed4-ecca-430a-b825-efb6f62d5efc%2Fmain%2F2.log%5C%22,job%3D%5C%22freetier-01%2Fdefault-cn%5C%22,lifecycle_apps_kruise_io_state%3D%5C%22Normal%5C%22,matrixone_cloud_cluster%3D%5C%22freetier-01%5C%22,matrixone_cloud_component%3D%5C%22cn%5C%22,matrixone_cloud_main_cluster%3D%5C%22freetier-01%5C%22,matrixone_cloud_profile%3D%5C%22cn.standard%5C%22,matrixorigin_io_component%3D%5C%22CNSet%5C%22,matrixorigin_io_instance%3D%5C%22default%5C%22,matrixorigin_io_namespace%3D%5C%22freetier-01%5C%22,namespace%3D%5C%22freetier-01%5C%22,node_name%3D%5C%22cn-hangzhou.10.3.138.70%5C%22,pod%3D%5C%22default-cn-5vzng%5C%22,pod_template_hash%3D%5C%2296868c55b%5C%22,stream%3D%5C%22stderr%5C%22%7D%22,%22queryType%22:%22range%22,%22refId%22:%22log-row-context-query-_0.7176575156773066%22,%22maxLines%22:1000,%22direction%22:%22backward%22,%22datasource%22:%7B%22uid%22:%22loki%22,%22type%22:%22loki%22%7D%7D%5D,%22range%22:%7B%22from%22:%221700639679759%22,%22to%22:%221700639679761%22%7D,%22panelsState%22:%7B%22logs%22:%7B%22id%22:%22log-row-context-query-_0.7176575156773066_1700639679761079680_544dc5c3%22%7D%7D%7D%7D&schemaVersion=1

**Comment by arjunsk** [comment] 2023-11-23 07:53
@nnsgmsone Kindly look into this.

**Comment by sukki37** [comment] 2024-03-26 09:26
The issue is outdated, and neither the context nor the environment has been preserved, making it impossible to locate. Close it for now. If it reoccurs, open a new issue.

**Closed by sukki37** 2024-03-26 09:26 UTC
Labels: kind/bug, team/c2, to-next-release, impact/1.1
