### ISSUE TITLE
[Bug]: panic cause by master-index case

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#14932] opened 2024-03-12 13:46 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8248562092/job/22561328352?pr=14913

[1-cn-e2e-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/14573686/1-cn-e2e-linux-x86-reports.zip)

<img width="865" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/090c6b20-641c-4da7-8ac4-3a81531556e6">

### Steps to Reproduce

```Markdown
run bvt
```

**Comment by arjunsk** [comment] 2024-03-12 18:59
duplicate of https://github.com/matrixorigin/matrixone/issues/14905

already working on the fix.

**Closed** 2024-03-13 01:19 UTC
Labels: kind/bug, severity/s0
