### ISSUE TITLE
[Bug]: BlockRead not use mpool

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#5937] opened 2022-10-25 05:23 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

blockio.Read not use mpool now?

**Comment by LeftHandCold** [comment] 2022-11-04 05:27
After communicating with @nnsgmsone , it can be adjusted to s1

**Comment by LeftHandCold** [comment] 2022-11-04 05:28
The root cause is that vector does not provide an interface for serialization and deserialization based on mpool

**Comment by LeftHandCold** [comment] 2022-11-10 14:37
Should be implemented in 0.7

**Comment by LeftHandCold** [comment] 2022-11-16 14:45
I didn't work on it today

**Comment by LeftHandCold** [comment] 2023-01-06 04:40
@nnsgmsone @zengyan1 After the vector is refactored, it will be fixed

**Closed** 2023-07-11 10:03 UTC
Labels: kind/bug, priority/p0, triage/accepted, being-discussed
