### ISSUE TITLE
[Bug]: many waitSendCompleted last minutes

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#13471] opened 2023-12-14 09:43 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

free01
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/34b3e3ff-575d-440b-bb32-735cd7212613)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/9fa52aa0-55d5-4e2d-a24b-8a3e545aa9cf)

http://132.232.112.34:30088/explore?panes=%7B%22xwd%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231206%5C%22,%20pod%3D%5C%22nightly-regression-dis-tp-cn-zfn7g%5C%22%7D%20%7C%3D%20%60waitSendCompleted%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701891001000%22,%22to%22:%221701894840000%22%7D%7D,%22BeE%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22expr%22:%22%7Bapp%3D%5C%22nightly-regression-dis-tp-cn%5C%22,apps_kruise_io_cloneset_instance_id%3D%5C%22zfn7g%5C%22,container%3D%5C%22main%5C%22,controller_revision_hash%3D%5C%22nightly-regression-dis-tp-cn-644bbc4f6c%5C%22,filename%3D%5C%22%2Fvar%2Flog%2Fpods%2Fmo-nightly-regression-20231206_nightly-regression-dis-tp-cn-zfn7g_a568a818-24ec-441b-b7ae-cd7c4f367e5a%2Fmain%2F0.log%5C%22,job%3D%5C%22mo-nightly-regression-20231206%2Fnightly-regression-dis-tp-cn%5C%22,lifecycle_apps_kruise_io_state%3D%5C%22Normal%5C%22,matrixorigin_io_cluster%3D%5C%22nightly-regression-dis%5C%22,matrixorigin_io_component%3D%5C%22CNSet%5C%22,matrixorigin_io_instance%3D%5C%22nightly-regression-dis-tp%5C%22,matrixorigin_io_namespace%3D%5C%22mo-nightly-regression-20231206%5C%22,namespace%3D%5C%22mo-nightly-regression-20231206%5C%22,node_name%3D%5C%2210.129.0.135%5C%22,pod%3D%5C%22nightly-regression-dis-tp-cn-zfn7g%5C%22,pod_template_hash%3D%5C%22644bbc4f6c%5C%22,stream%3D%5C%22stderr%5C%22%7D%22,%22queryType%22:%22range%22,%22refId%22:%22log-row-context-query-_0.1890668760358547%22,%22maxLines%22:1000,%22direction%22:%22backward%22,%22datasource%22:%7B%22uid%22:%22loki%22,%22type%22:%22loki%22%7D%7D%5D,%22range%22:%7B%22from%22:%221701892561914%22,%22to%22:%221701892561914%22%7D%7D%7D&schemaVersion=1&orgId=1

### Expected Behavior

no wait

**Comment by zhangxu19830126** [comment] 2023-12-15 03:08
github.com/matrixorigin/matrixone/pkg/util/profile.ProfileGoroutine(...)
2023-12-07 04:24:24.109	
	/go/src/github.com/matrixorigin/matrixone/pkg/util/profile/profile.go:42
2023-12-07 04:24:24.109	
github.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).writeLoop(0xc3cfb98340, {0xc62a446630?, 0x0?})
2023-12-07 04:24:24.109	
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:465 +0x66d


caused by stw profile goroutines. this is fixed by #13320

**Closed** 2024-05-15 02:10 UTC
Labels: kind/bug, team/c2
