### ISSUE TITLE
[Bug]:  Server crashed after loading data into server

### ISSUE THREAD

**Issue by sundy-li** [matrixorigin/matrixone#1703] opened 2022-02-13 07:17 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):  d099c08c0b9abd7659dc6ac8b785214e121e3639
- Hardware parameters: 
- OS type: archlinux
- Others:
```

### Actual Behavior

```
{"level":"INFO","time":"2022/02/13 15:11:13.117327 +0800","caller":"aoe/storage.go:473","msg":"GetInitialStates LogIndex is 1, ShardID is 45, Metadata is shard:<id:45 start:\"aoe-\\000\\000\\000\\000\\000\\000\\000\\025\" end:\"aoe-\\000\\000\\000\\000\\000\\000\\000\\026\" epoch:<confVer:1 > state:Creating replicas:<id:46 containerID:1 initialMember:true > group:1 unique:\"1-1-21\" > \n"}
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/matrixorigin/matrixone/pkg/vm/driver/aoe.(*Storage).GetInitialStates(0xc002dae1b0)
        /home/sundy/work/matrixone/pkg/vm/driver/aoe/storage.go:450 +0xba5
github.com/matrixorigin/matrixcube/raftstore.(*store).startShards.func1({0x2809778, 0xc002dae1b0})
        /home/sundy/gopath/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/store.go:430 +0x8e
github.com/matrixorigin/matrixone/pkg/vm/driver.NewCubeDriverWithFactory.func2(0xc002ccb900)
        /home/sundy/work/matrixone/pkg/vm/driver/cube_driver.go:192 +0x53
github.com/matrixorigin/matrixcube/raftstore.(*store).startShards(0xc0001ce380)
        /home/sundy/gopath/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/store.go:429 +0x19e
github.com/matrixorigin/matrixcube/raftstore.(*store).Start(0xc0001ce380)
        /home/sundy/gopath/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/store.go:185 +0x6f2
github.com/matrixorigin/matrixcube/server.(*Application).Start(0xc003058a80)
        /home/sundy/gopath/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/server/server.go:84 +0x86
github.com/matrixorigin/matrixone/pkg/vm/driver.(*driver).Start(0xc002d9d180)
        /home/sundy/work/matrixone/pkg/vm/driver/cube_driver.go:251 +0x3a
main.main()
        /home/sundy/work/matrixone/cmd/db-server/main.go:253 +0xe56
❯
```

### Steps to Reproduce

```markdown
Follow the ssb benchmark docs in https://docs.matrixorigin.io/0.2.0/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone/#3-create-tables-in-matrixone

Load the data using:


load data infile '/ssb-dbgen-path/lineorder_flat.tbl ' into table lineorder_flat FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';

```

Then the server crashed and I restarted the matrix-server, client can't connect to the server again. BTW how to cleanup the data && metadata in matrixone?
```


### Additional information

_No response_

**Comment by sundy-li** [comment] 2022-02-13 12:21
```
MySQL [tmp]> load data infile '/home/sundy/lineorder_flat.tbl' into table lineorder_flat FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
ERROR 2013 (HY000): Lost connection to server during query
MySQL [tmp]>
```

```
{"level":"DEBUG","time":"2022/02/13 20:20:55.909174 +0800","name":"cube.store.proxy","caller":"raftstore/proxy.go:354","msg":"dispatch request failed, retry later","store":"node0","store-id":1,"id":"248fb5a813c64be7859e5c1c25a9da10","cause":"dispath to nil store"}
{"level":"DEBUG","time":"2022/02/13 20:20:55.946861 +0800","name":"cube.store","caller":"raftstore/replica_destroy_task.go:283","msg":"log applied","store":"node0","store-id":1,"shard-id":5,"replica-id":9,"task":"destroy-shard-task"}
{"level":"DEBUG","time":"2022/02/13 20:20:55.946932 +0800","name":"cube.prophet","caller":"prophet/prophet_handler.go:50","msg":"rpc request received","node":"node0","id":112,"from":"127.0.0.1:33786","type":"TypeReportDestroyedReq"}
{"level":"FATAL","time":"2022/02/13 20:20:55.946950 +0800","name":"cube.prophet.raft-cluster","caller":"cluster/cluster_worker.go:429","msg":"missing resource to set destroyed","node":"node0","resource":5}
```

**Comment by LeftHandCold** [comment] 2022-02-14 04:53
The mo-server crashed when the cube called saveShardMetadata, which caused aoe to only store the metadata and not the data, so the cube called GetInitialStates to crash, which needs to be avoided.

**Comment by sundy-li** [comment] 2022-02-17 01:30
@LeftHandCold  

Hello, I do not think this issue can be closed, because the main problem of the loading bug is not resolved.

**Comment by LeftHandCold** [comment] 2022-02-17 02:41
> {"level":"DEBUG","time":"2022/02/13 20:20:55.909174 +0800","name":"cube.store.proxy","caller":"raftstore/proxy.go:354","msg":"dispatch request failed, retry later","store":"node0","store-id":1,"id":"248fb5a813c64be7859e5c1c25a9da10","cause":"dispath to nil store"}
> {"level":"DEBUG","time":"2022/02/13 20:20:55.946861 +0800","name":"cube.store","caller":"raftstore/replica_destroy_task.go:283","msg":"log applied","store":"node0","store-id":1,"shard-id":5,"replica-id":9,"task":"destroy-shard-task"}
> {"level":"DEBUG","time":"2022/02/13 20:20:55.946932 +0800","name":"cube.prophet","caller":"prophet/prophet_handler.go:50","msg":"rpc request received","node":"node0","id":112,"from":"127.0.0.1:33786","type":"TypeReportDestroyedReq"}
> {"level":"FATAL","time":"2022/02/13 20:20:55.946950 +0800","name":"cube.prophet.raft-cluster","caller":"cluster/cluster_worker.go:429","msg":"missing resource to set destroyed","node":"node0","resource":5}

@sundy-li When #1707 is merged and the "store" directory is deleted, will the problem still occur?

**Comment by sundy-li** [comment] 2022-02-17 02:45
Yes. I just tested with the latest build.

**Comment by LeftHandCold** [comment] 2022-02-17 11:07
@sundy-li 
Need to delete the "store" directory,Execute "make config&make build".
This error looks like there should be previous residual data.I can't reproduce it according to the description, please upload the log of loading error.

**Comment by sundy-li** [comment] 2022-02-17 12:02
Yes,  Same error as I paste before.

```
git pull origin main
 rm -rf store
 make config && make build

load data infile '/home/sundy/lineorder_flat.tbl' into table lineorder_flat FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';

```
logs:
```
{"level":"DEBUG","time":"2022/02/17 19:12:29.345338 +0800","name":"cube.store.proxy","caller":"raftstore/proxy.go:354","msg":"dispatch request failed, retry later","store":"node0","store-id":1,"id":"c4d6cf96a5494c69af6fedf7712f643b","cause":"dispath to nil store"}
{"level":"DEBUG","time":"2022/02/17 19:12:29.345343 +0800","name":"cube.store.router","caller":"raftstore/router.go:434","msg":"missing leader","store":"node0","shard-id":0}
{"level":"DEBUG","time":"2022/02/17 19:12:29.345346 +0800","name":"cube.store.proxy","caller":"raftstore/proxy.go:215","msg":"dispatch request","store":"node0","store-id":1,"id":"328bf183ea1a45548737aa36dd6c55f2","to-shard":0,"to-store":"","request":"id: 328bf183ea1a45548737aa36dd6c55f2, key: , pid: 0, type: Write, custom-type: 100, cmd: 16579229 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/02/17 19:12:29.345351 +0800","name":"cube.store.proxy","caller":"raftstore/proxy.go:354","msg":"dispatch request failed, retry later","store":"node0","store-id":1,"id":"328bf183ea1a45548737aa36dd6c55f2","cause":"dispath to nil store"}
{"level":"DEBUG","time":"2022/02/17 19:12:29.345359 +0800","name":"cube.store.router","caller":"raftstore/router.go:434","msg":"missing leader","store":"node0","shard-id":0}
{"level":"DEBUG","time":"2022/02/17 19:12:29.345363 +0800","name":"cube.store.proxy","caller":"raftstore/proxy.go:215","msg":"dispatch request","store":"node0","store-id":1,"id":"e793481af9dc4c82ae52e41f9e097688","to-shard":0,"to-store":"","request":"id: e793481af9dc4c82ae52e41f9e097688, key: , pid: 0, type: Write, custom-type: 100, cmd: 16577252 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/02/17 19:12:29.345368 +0800","name":"cube.store.proxy","caller":"raftstore/proxy.go:354","msg":"dispatch request failed, retry later","store":"node0","store-id":1,"id":"e793481af9dc4c82ae52e41f9e097688","cause":"dispath to nil store"}
{"level":"DEBUG","time":"2022/02/17 19:12:29.345373 +0800","name":"cube.store.router","caller":"raftstore/router.go:434","msg":"missing leader","store":"node0","shard-id":0}
{"level":"DEBUG","time":"2022/02/17 19:12:29.345376 +0800","name":"cube.store.proxy","caller":"raftstore/proxy.go:215","msg":"dispatch request","store":"node0","store-id":1,"id":"a3163640b50c40c0b8df1e68e40490b9","to-shard":0,"to-store":"","request":"id: a3163640b50c40c0b8df1e68e40490b9, key: , pid: 0, type: Write, custom-type: 100, cmd: 16576914 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/02/17 19:12:29.345381 +0800","name":"cube.store.proxy","caller":"raftstore/proxy.go:354","msg":"dispatch request failed, retry later","store":"node0","store-id":1,"id":"a3163640b50c40c0b8df1e68e40490b9","cause":"dispath to nil store"}
{"level":"DEBUG","time":"2022/02/17 19:12:29.345387 +0800","name":"cube.store.router","caller":"raftstore/router.go:434","msg":"missing leader","store":"node0","shard-id":0}
{"level":"DEBUG","time":"2022/02/17 19:12:29.345391 +0800","name":"cube.store.proxy","caller":"raftstore/proxy.go:215","msg":"dispatch request","store":"node0","store-id":1,"id":"3254791041934d128d0969f8584345f7","to-shard":0,"to-store":"","request":"id: 3254791041934d128d0969f8584345f7, key: , pid: 0, type: Write, custom-type: 100, cmd: 16574602 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/02/17 19:12:29.345398 +0800","name":"cube.store.proxy","caller":"raftstore/proxy.go:354","msg":"dispatch request failed, retry later","store":"node0","store-id":1,"id":"3254791041934d128d0969f8584345f7","cause":"dispath to nil store"}
{"level":"DEBUG","time":"2022/02/17 19:12:29.380085 +0800","name":"cube.store","caller":"raftstore/replica_destroy_task.go:283","msg":"log applied","store":"node0","store-id":1,"shard-id":5,"replica-id":9,"task":"destroy-shard-task"}
{"level":"DEBUG","time":"2022/02/17 19:12:29.380249 +0800","name":"cube.prophet","caller":"prophet/prophet_handler.go:50","msg":"rpc request received","node":"node0","id":112,"from":"127.0.0.1:47526","type":"TypeReportDestroyedReq"}
{"level":"FATAL","time":"2022/02/17 19:12:29.380278 +0800","name":"cube.prophet.raft-cluster","caller":"cluster/cluster_worker.go:429","msg":"missing resource to set destroyed","node":"node0","resource":5}
```

**Comment by LeftHandCold** [comment] 2022-02-18 03:32
@sundy-li 
Hello,I reproduced the issue on hdd.You can change the "loadDataConcurrencyCount = 4" in "system_vars_config.toml" file to continue loading, I will continue to track this issue.

**Comment by zhangxu19830126** [comment] 2022-02-24 11:45
MatrixCube has been updated, since the splitting of `Shard` of `MatrixCube` will delete the original `Shard`, so the original `Shard` cannot provide read/write, you need to manipulate data on the split Shard. If a read/write operation is performed on the deleted `Shard`, `MatrixCube` will return `UnavailableShardErr`, `MatrixOne` needs to sense this error and modify the operation to the correct `Shard`

Translated with www.DeepL.com/Translator (free version)

**Comment by yingfeng** [comment] 2022-03-08 11:52
Could not reproduce after above PRs' having been applied, and extra #1832 and #1840

**Closed** 2022-03-09 13:53 UTC
Labels: kind/bug, triage/accepted
