### ISSUE TITLE
[Feature Request]: Decimal support operator of mod

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#4432] opened 2022-08-09 08:15 UTC
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

select cast(10000002383263201056 as decimal) mod 50 as result;

**Comment by aunjgr** [comment] 2022-11-21 11:02
It's in the scope of #4241.

**Comment by aunjgr** [comment] 2022-11-25 13:10
Will be resolved by #4241.

**Comment by aunjgr** [comment] 2022-12-01 14:50
It's a duplicate of #4241. Can be closed.

**Comment by matrix-meow** [comment] 2022-12-05 11:52
Hello @iamlinjunhong. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by matrix-meow** [comment] 2022-12-07 11:13
Hello @iamlinjunhong. The bug issue in the BVT test code has not been removed,issues automatically open.

**Closed** 2022-12-30 06:19 UTC
Labels: kind/feature, severity/s1, bvt
