### ISSUE TITLE
[Bug]:run TPCH100 on eks RC with 1CN:  Can't connect to MySQL server on 'ip:6001'

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11221] opened 2023-08-15 04:06 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): auto-test-918bf5f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="650" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/14709a8e-fc06-4de0-b7ec-45899e6e9e80">

<img width="1165" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/63c9785d-4eb3-453f-9c7c-de29c10846b0">

log：http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bnamespace%3D%5C%22weilu%5C%22,%20pod%3D%5C%22perfwl-tp-cn-vk6hj%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

memory use：http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=Prometheus&var-cluster=&var-namespace=weilu&from=now-1h&to=now

[test.yaml.zip](https://github.com/matrixorigin/matrixone/files/12341096/test.yaml.zip)

**Comment by aronchanisme** [comment] 2023-08-15 06:11
**Analysis**
Cannot connect to MO is due to CN's restart during the time when query is running. Need to verify why cn is restarted.  Time is around `8/15 11:38 utc+8`
<img width="713" alt="企业微信截图_3433177d-0d6e-4250-88d0-2bb91c42c777" src="https://github.com/matrixorigin/matrixone/assets/46433151/4ea276f5-c09b-4cd5-a957-ba4429791756">

1. Previous emory usage reached 53.4GB, while request is set to 50GB and limit set to 64GB
<img width="1897" alt="企业微信截图_17dbb98d-260d-46ed-a2a4-e17fc417b47a" src="https://github.com/matrixorigin/matrixone/assets/46433151/b7a2f909-1dcb-42c2-91ef-e4ab0448433c">
<img width="604" alt="企业微信截图_00aca842-9dbd-4651-96ba-35746f8699b5" src="https://github.com/matrixorigin/matrixone/assets/46433151/a7d2a54c-d8e0-4c27-bdac-b6d0c5786414">


2. From logs of cn pod `perfwl-tp-cn-xthcd`, cn seems to be shutown abnormally, without any keywords of 'Shutdown complete'

<img width="566" alt="企业微信截图_4692519c-983a-4964-b527-fc46dbf2637f" src="https://github.com/matrixorigin/matrixone/assets/46433151/eaa5ecb3-b668-4047-8cd6-66a31c6ce166">

<img width="1913" alt="企业微信截图_ed818195-86d5-4d4c-844f-5fbe7a0c2315" src="https://github.com/matrixorigin/matrixone/assets/46433151/1fa43b68-40d6-435b-b435-47519826e4ce">


3. But `kubectl get event -nweilu` shows no record related to `oomkilled`, which is wired
<img width="1896" alt="企业微信截图_bcc57e7c-19a7-4089-8881-a42a898d1ee2" src="https://github.com/matrixorigin/matrixone/assets/46433151/c71e3298-5820-48ec-a7c5-c5f5d06e0601">



**Next Action Plan**
Suggestion to modify cn's resources settting is provided. Please reconfigure the cluster and test again if cn pod will be restarted again.
```yaml
resources:
      requests:
        cpu: 16
        memory: 64Gi
      limits:
        cpu: 16
        memory: 64Gi
```

**Comment by aronchanisme** [comment] 2023-08-15 07:34
@nnsgmsone Please kindly take a look. It's an OOM issue when running tpch 100g query. 50Gi memory is exeeded and cn pod is killed due to oom. 

Re-run tpch 100g query test again, with below cn setting
```yaml
resources:
      requests:
        cpu: 15
        memory: 50Gi
      limits:
        cpu: 15
        memory: 50Gi
```

We confirmed cn is `oomkilled` by kubernetes
<img width="1913" alt="企业微信截图_9c82e90b-91d7-4f13-8f2f-23131c1d6476" src="https://github.com/matrixorigin/matrixone/assets/46433151/fba661a7-1849-4098-995b-6119c50ee21e">
<img width="1405" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/b7b8b4f8-ee76-4e5e-a55c-3ea23048a2e8">

Attaching cn log.
[cn.log.txt](https://github.com/matrixorigin/matrixone/files/12342081/cn.log.txt)

**Comment by Ariznawlll** [comment] 2023-08-15 07:34
<img width="1432" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/0dd26b10-9b55-450f-bc02-35dc8cea7111">
log：http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bnamespace%3D%5C%22weilu%5C%22,%20pod%3D%5C%22perfwl-tp-cn-62w2j%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

memory use：http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&refresh=10s&var-datasource=Prometheus&var-cluster=&var-namespace=weilu

[test.yaml.zip](https://github.com/matrixorigin/matrixone/files/12342091/test.yaml.zip)

**Comment by Ariznawlll** [comment] 2023-08-15 07:36
[test.yaml.zip](https://github.com/matrixorigin/matrixone/files/12342091/test.yaml.zip)

**Comment by aronchanisme** [comment] 2023-08-15 07:40
memCache is set to `12Gi`
<img width="616" alt="企业微信截图_6cd5ffbe-e916-4ed6-a195-9471fbf2be08" src="https://github.com/matrixorigin/matrixone/assets/46433151/eb2bf73d-abff-4fa0-af3f-e9a84a59bb8e">

env `GOLIMIT` is also set, whose value is `5000MiB`. Even so, we still get oom issue.
<img width="616" alt="企业微信截图_6cd5ffbe-e916-4ed6-a195-9471fbf2be08" src="https://github.com/matrixorigin/matrixone/assets/46433151/d2824c70-4b43-4510-8fd6-7957a6e3fd1a">

**Comment by badboynt1** [comment] 2023-08-15 07:42
gomemlimit 距离 limit太近了。 把gomemlimit设置成45g， request和limit设置成55g试试看？

**Comment by nnsgmsone** [comment] 2023-08-16 10:12
先设置GOMEMLIMIT和调小cache大小跑吧。。

**Comment by sukki37** [comment] 2023-08-16 14:01
which can be temporarily resolved by modifying the configuration, tracked by #10945

**Comment by nnsgmsone** [comment] 2023-11-27 10:20
dup with #10945

**Closed** 2023-11-29 09:38 UTC
Labels: kind/bug, severity/s0, area/memory, team/c2
