### ISSUE TITLE
[Bug]:  Concurrent query performance issues on `system_metric` tables

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#7334] opened 2022-12-27 03:26 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):f9c8999675def9c7be9ad37703f23a3b4769a2c7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When I execute multiple(2 or 3) SQLs simultaneously, each SQL takes several times longer than executed individually.
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/77312370/209606823-2210e60f-36c7-4870-8c4c-9678ca50cc94.png">

### Steps to Reproduce

```Markdown
Execute the following SQLs in two ways:
1. one by one
2. concurrently

You can see the severe performance degradation.


USE system_metrics; SELECT `stat_ts`, SUM(`value`) as value, `type` FROM(SELECT concat(DATE_FORMAT(collecttime,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(collecttime) / 10),2,0),':00') AS stat_ts, SUM(`value`) AS value, `node`, `type` FROM sql_statement_total WHERE `collecttime` >= '2022-12-25 00:40:00' AND `collecttime` <= '2022-12-27 00:00:00' AND `type` in ('DDL','DML') GROUP BY `node`,`type`, concat(DATE_FORMAT(collecttime,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(collecttime) / 10),2,0),':00')  ORDER BY concat(DATE_FORMAT(collecttime,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(collecttime) / 10),2,0),':00') LIMIT 100)t GROUP BY `stat_ts`,`type`;

USE system_metrics; SELECT `stat_ts`, SUM(`value`) as value, `type` FROM(SELECT concat(DATE_FORMAT(collecttime,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(collecttime) / 10),2,0),':00') AS stat_ts, AVG(`value`) AS value, `node`, `type` FROM sql_statement_total WHERE `collecttime` >= '2022-12-25 00:40:00' AND `collecttime` <= '2022-12-27 00:00:00' AND `type` in ('DDL','DML') GROUP BY `node`,`type`, concat(DATE_FORMAT(collecttime,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(collecttime) / 10),2,0),':00')  ORDER BY concat(DATE_FORMAT(collecttime,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(collecttime) / 10),2,0),':00') LIMIT 100)t GROUP BY `stat_ts`,`type`;

USE system_metrics; SELECT `stat_ts`, sum(`value`) as value FROM(SELECT concat(DATE_FORMAT(collecttime,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(collecttime) / 10),2,0),':00') AS stat_ts, AVG(`value`) AS value, `node` FROM server_connections WHERE `collecttime` >= '2022-12-25 00:40:00' AND `collecttime` <= '2022-12-27 00:00:00' GROUP BY `node`, concat(DATE_FORMAT(collecttime,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(collecttime) / 10),2,0),':00')  ORDER BY concat(DATE_FORMAT(collecttime,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(collecttime) / 10),2,0),':00') LIMIT 100)t GROUP BY `stat_ts`;
```

**Comment by sukki37** [comment] 2023-01-06 08:58
mock code: 

```go
package main

import (
	"context"
	"emperror.dev/emperror"
	"github.com/matrixone-cloud/mocloud-services/src/common/db"
	"golang.org/x/sync/errgroup"
	"logging"
)

func main() {

	maxConcurrentNum := 10
	c, err := db.OpenDB(db.Config{
		Host:     "127.0.0.1",
		Port:     6001,
		Username: "dump",
		Password: "111",
		Database: "system_",
	}, logging.New(logging.GetGlobalLogger()))

	sqls := []string{
		"USE system;  SELECT concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') AS stat_ts, AVG(duration) AS value, `query_type` AS type FROM statement_info WHERE request_at >= '2022-12-27 00:40:00' AND request_at <= '2023-12-28 00:00:00' AND `query_type` in ('DDL','DML') GROUP BY `query_type`, concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') ORDER BY concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') LIMIT 100;",
	}

	emperror.Panic(err)

	eg, _ := errgroup.WithContext(context.Background())

	for _, sql := range sqls {
		cSql := sql
		for i := 0; i < maxConcurrentNum; i++ {
			eg.Go(func() error {

				if err != nil {
					return err
				}
				result := make([]map[string]interface{}, 0)
				err = c.Raw(cSql).Debug().Scan(&result).Error
				//fmt.Printf("%v\n", result)
				return err

			})
		}

	}

	if err := eg.Wait(); err != nil {
		emperror.Panic(err)
	}

}

```

you can see the huge performance gap when you change `maxConcurrentNum` to 1. On my scenario, when `maxConcurrentNum=1`, the SQL cost 300ms, when `maxConcurrentNum=10` the same SQL costes 1s+.

log of `maxConcurrentNum=1`
```shell
/usr/local/go/bin/go build -o /private/var/folders/v4/9c736kps76jbbvf97snf3s9w0000gn/T/GoLand/___go_build_github_com_matrixone_cloud_mocloud_services_src_local_service_test github.com/matrixone-cloud/mocloud-services/src/local-service/test #gosetup
/private/var/folders/v4/9c736kps76jbbvf97snf3s9w0000gn/T/GoLand/___go_build_github_com_matrixone_cloud_mocloud_services_src_local_service_test
2023/01/06 16:54:12.597494 +0800 WARN errgroup/errgroup.go:75 trace {"elapsed": "321.503208ms", "rows": 4, "sql": "USE system;  SELECT concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') AS stat_ts, AVG(duration) AS value, `query_type` AS type FROM statement_info WHERE request_at >= '2022-12-27 00:40:00' AND request_at <= '2023-12-28 00:00:00' AND `query_type` in ('DDL','DML') GROUP BY `query_type`, concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') ORDER BY concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') LIMIT 100;"}
```

log of `maxConcurrentNum=10`
```
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/maomao/go #gosetup
/usr/local/go/bin/go build -o /private/var/folders/v4/9c736kps76jbbvf97snf3s9w0000gn/T/GoLand/___go_build_github_com_matrixone_cloud_mocloud_services_src_local_service_test github.com/matrixone-cloud/mocloud-services/src/local-service/test #gosetup
/private/var/folders/v4/9c736kps76jbbvf97snf3s9w0000gn/T/GoLand/___go_build_github_com_matrixone_cloud_mocloud_services_src_local_service_test
2023/01/06 16:52:45.825255 +0800 WARN errgroup/errgroup.go:75 trace {"elapsed": "1.063741875s", "rows": 4, "sql": "USE system;  SELECT concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') AS stat_ts, AVG(duration) AS value, `query_type` AS type FROM statement_info WHERE request_at >= '2022-12-27 00:40:00' AND request_at <= '2023-12-28 00:00:00' AND `query_type` in ('DDL','DML') GROUP BY `query_type`, concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') ORDER BY concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') LIMIT 100;"}
2023/01/06 16:52:45.833540 +0800 WARN errgroup/errgroup.go:75 trace {"elapsed": "1.071735209s", "rows": 4, "sql": "USE system;  SELECT concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') AS stat_ts, AVG(duration) AS value, `query_type` AS type FROM statement_info WHERE request_at >= '2022-12-27 00:40:00' AND request_at <= '2023-12-28 00:00:00' AND `query_type` in ('DDL','DML') GROUP BY `query_type`, concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') ORDER BY concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') LIMIT 100;"}
2023/01/06 16:52:45.841793 +0800 WARN errgroup/errgroup.go:75 trace {"elapsed": "1.0804155s", "rows": 4, "sql": "USE system;  SELECT concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') AS stat_ts, AVG(duration) AS value, `query_type` AS type FROM statement_info WHERE request_at >= '2022-12-27 00:40:00' AND request_at <= '2023-12-28 00:00:00' AND `query_type` in ('DDL','DML') GROUP BY `query_type`, concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') ORDER BY concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') LIMIT 100;"}
2023/01/06 16:52:45.865158 +0800 WARN errgroup/errgroup.go:75 trace {"elapsed": "1.103564875s", "rows": 4, "sql": "USE system;  SELECT concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') AS stat_ts, AVG(duration) AS value, `query_type` AS type FROM statement_info WHERE request_at >= '2022-12-27 00:40:00' AND request_at <= '2023-12-28 00:00:00' AND `query_type` in ('DDL','DML') GROUP BY `query_type`, concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') ORDER BY concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') LIMIT 100;"}
2023/01/06 16:52:45.869144 +0800 WARN errgroup/errgroup.go:75 trace {"elapsed": "1.107761959s", "rows": 4, "sql": "USE system;  SELECT concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') AS stat_ts, AVG(duration) AS value, `query_type` AS type FROM statement_info WHERE request_at >= '2022-12-27 00:40:00' AND request_at <= '2023-12-28 00:00:00' AND `query_type` in ('DDL','DML') GROUP BY `query_type`, concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') ORDER BY concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') LIMIT 100;"}
2023/01/06 16:52:45.881052 +0800 WARN errgroup/errgroup.go:75 trace {"elapsed": "1.119368833s", "rows": 4, "sql": "USE system;  SELECT concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') AS stat_ts, AVG(duration) AS value, `query_type` AS type FROM statement_info WHERE request_at >= '2022-12-27 00:40:00' AND request_at <= '2023-12-28 00:00:00' AND `query_type` in ('DDL','DML') GROUP BY `query_type`, concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') ORDER BY concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') LIMIT 100;"}
2023/01/06 16:52:45.884917 +0800 WARN errgroup/errgroup.go:75 trace {"elapsed": "1.123541917s", "rows": 4, "sql": "USE system;  SELECT concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') AS stat_ts, AVG(duration) AS value, `query_type` AS type FROM statement_info WHERE request_at >= '2022-12-27 00:40:00' AND request_at <= '2023-12-28 00:00:00' AND `query_type` in ('DDL','DML') GROUP BY `query_type`, concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') ORDER BY concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') LIMIT 100;"}
2023/01/06 16:52:45.888799 +0800 WARN errgroup/errgroup.go:75 trace {"elapsed": "1.126871125s", "rows": 4, "sql": "USE system;  SELECT concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') AS stat_ts, AVG(duration) AS value, `query_type` AS type FROM statement_info WHERE request_at >= '2022-12-27 00:40:00' AND request_at <= '2023-12-28 00:00:00' AND `query_type` in ('DDL','DML') GROUP BY `query_type`, concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') ORDER BY concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') LIMIT 100;"}
2023/01/06 16:52:45.900827 +0800 WARN errgroup/errgroup.go:75 trace {"elapsed": "1.138958708s", "rows": 4, "sql": "USE system;  SELECT concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') AS stat_ts, AVG(duration) AS value, `query_type` AS type FROM statement_info WHERE request_at >= '2022-12-27 00:40:00' AND request_at <= '2023-12-28 00:00:00' AND `query_type` in ('DDL','DML') GROUP BY `query_type`, concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') ORDER BY concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') LIMIT 100;"}
2023/01/06 16:52:45.903518 +0800 WARN errgroup/errgroup.go:75 trace {"elapsed": "1.141713791s", "rows": 4, "sql": "USE system;  SELECT concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') AS stat_ts, AVG(duration) AS value, `query_type` AS type FROM statement_info WHERE request_at >= '2022-12-27 00:40:00' AND request_at <= '2023-12-28 00:00:00' AND `query_type` in ('DDL','DML') GROUP BY `query_type`, concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') ORDER BY concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') LIMIT 100;"}

Process finished with the exit code 0
```

**Comment by nnsgmsone** [comment] 2023-01-13 10:58
No progress at the moment

**Comment by reusee** [comment] 2023-01-16 09:09
Reproduction program:
```
package main

import (
	"database/sql"
	"fmt"
	"time"

	_ "github.com/go-sql-driver/mysql"
)

func main() {
	c, err := sql.Open("mysql", "dump:111@tcp(127.0.0.1:6001)/test")
	if err != nil {
		panic(err)
	}
	if err := c.Ping(); err != nil {
		panic(err)
	}

	maxConcurrentNum := 100
	sqls := []string{
		"USE system;  SELECT concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') AS stat_ts, AVG(duration) AS value, `query_type` AS type FROM statement_info WHERE request_at >= '2022-12-27 00:40:00' AND request_at <= '2023-12-28 00:00:00' AND `query_type` in ('DDL','DML') GROUP BY `query_type`, concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') ORDER BY concat(DATE_FORMAT(`request_at`,'%Y-%m-%d %H'),':',LPAD(10 * floor(minute(`request_at`) / 10),2,0),':00') LIMIT 100;",
	}

	sem := make(chan struct{}, maxConcurrentNum)
	const numRuns = 10000

	for i := 0; i < numRuns; i++ {
		i := i
		sem <- struct{}{}
		go func() {
			defer func() {
				<-sem
			}()

			t0 := time.Now()
			n := 0
			for _, sql := range sqls {
				rows, err := c.Query(sql)
				if err != nil {
					panic(err)
				}
				var date string
				var duration float64
				var queryType string
				for rows.Next() {
					n++
					if err := rows.Scan(&date, &duration, &queryType); err != nil {
						panic(err)
					}
				}
				if err := rows.Err(); err != nil {
					panic(err)
				}
			}
			fmt.Printf("run %v done in %v, got %v rows\n", i, time.Since(t0), n)

		}()
	}

	for i := 0; i < cap(sem); i++ {
		sem <- struct{}{}
	}

}

```

**Comment by reusee** [comment] 2023-01-16 09:26
CPU profile:

<img width="1106" alt="截屏2023-01-16 17 20 48" src="https://user-images.githubusercontent.com/398457/212642424-3015b838-ada4-44c0-aec5-24b13c303d9d.png">

Seems OK.

Goroutine profile:
<img width="1108" alt="截屏2023-01-16 17 24 44" src="https://user-images.githubusercontent.com/398457/212643231-4367fb6d-3467-4c4e-9d38-708fd126b535.png">

Getting 326464 goroutine at simdcsv.Reader.Close:

<img width="786" alt="截屏2023-01-16 17 26 04" src="https://user-images.githubusercontent.com/398457/212643633-f9f2801e-ec47-4b89-ade1-8aa95da06a35.png">

**Comment by reusee** [comment] 2023-01-16 09:58
I commented out the codes in simdcsv.Reader.Close and re-run the test, it still gets slower and slower. The root cause is not the leak.

**Comment by reusee** [comment] 2023-01-17 03:46
`disttae.DB.Update` is getting slower.

<img width="738" alt="截屏2023-01-17 11 45 43" src="https://user-images.githubusercontent.com/398457/212805483-820c8203-a666-4976-acb1-04660da8236f.png">

**Comment by reusee** [comment] 2023-01-17 04:07
I believe the root cause is a lock contention here:
https://github.com/matrixorigin/matrixone/blob/090a774f43f5cd8006e0c8b27d555a0e13a1b3bc/pkg/vm/engine/disttae/db.go#L309

A trace sample:
<img width="740" alt="截屏2023-01-17 12 06 23" src="https://user-images.githubusercontent.com/398457/212807804-ff740674-39da-4711-bc86-0824e369989a.png">

The debugging branch is at: https://github.com/reusee/matrixone/tree/issue7334

**Comment by nnsgmsone** [comment] 2023-01-17 05:52
The problem should be solved after modifying it to a push model.

**Comment by m-schen** [comment] 2023-01-18 09:48
verify it after push model is ok. maybe very soon ?

**Comment by nnsgmsone** [comment] 2023-01-28 08:47
no process

**Comment by nnsgmsone** [comment] 2023-02-01 09:24
wait push model

**Comment by nnsgmsone** [comment] 2023-02-09 03:44
This can be converted to a feature

**Comment by nnsgmsone** [comment] 2023-02-17 14:53
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment] 2023-02-20 09:00
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment] 2023-02-23 09:18
wait for push modle

**Comment by m-schen** [comment] 2023-02-27 13:21
as nnsgmsone says, we will test it after push model #6894 was done.

**Comment by m-schen** [comment] 2023-03-01 13:52
as nnsgmsone says, we will test it after push model https://github.com/matrixorigin/matrixone/issues/6894 was done.

**Comment by m-schen** [comment] 2023-03-03 13:45
as nnsgmsone says, we will test it after push model was done.

**Comment by m-schen** [comment] 2023-03-06 12:12
as nnsgmsone says, we will test it after push model was done.

**Comment by m-schen** [comment] 2023-03-08 12:13
as nnsgmsone says, we will test it after push model was done.

**Comment by m-schen** [comment] 2023-03-13 13:45
到时候和pu sh一起送测

**Comment by m-schen** [comment] 2023-03-15 13:32
push基本功能已经完成，可以验证一下这个issue。

**Comment by aressu1985** [comment] 2023-03-17 00:43
@heni02 pls verify this issue

**Comment by heni02** [comment] 2023-03-21 11:57
confirm,closed
commit id:5265933d7a097a964fb4cfc126fe034789f3f6bf
![image](https://user-images.githubusercontent.com/113406637/226598928-f8a3eda8-e343-4cbc-b29d-afd2cfcdf2cd.png)
![image](https://user-images.githubusercontent.com/113406637/226599168-40ecbff3-188f-4fcc-ad00-d8ecef4123b2.png)
![image](https://user-images.githubusercontent.com/113406637/226599248-8b87bda5-3f87-44bf-8ba0-0926e6410b97.png)

**Comment by heni02** [comment] 2023-03-21 11:58
@aressu1985 plz close this issue

**Closed** 2023-03-22 01:11 UTC
Labels: kind/bug, needs-triage, severity/s0
