### ISSUE TITLE
[Tech Request]: chaos test kill dn + insert data to table, cn is not available (3mins+)

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#19472] opened 2024-10-19 09:47 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ec0a791e6fe0ecb1cc2ba3c233289164f55574c0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ERROR 20101 (HY000): internal error: no available CN server

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/mo-nightly-regression/actions/workflows/mo-chaos-test-on-distributed.yaml
1、use mo-chaos
   kill dn 
   use mo-load insert data to table
```

### Additional information

<img width="891" alt="image" src="https://github.com/user-attachments/assets/52ed0f99-ac19-42ae-bae8-0928823865c9">

<img width="1015" alt="image" src="https://github.com/user-attachments/assets/8f098da2-8af0-403b-8232-2cf5d433fc23">

**Comment by aylei** [comment] 2024-10-22 09:17
From the perspective of CN, forcibly deleting TN will cause all TCP connections to TN to receive no response. At this time, the TCP connection needs to reach the retransmission times defined by `net.ipv4.tcp_retries2` before the connection is disconnected. This process takes about 5 minutes. 

From the logs of CN and TN https://shanghai.idc.matrixorigin.cn:30001/goto/hwtp09mHg?orgId=1, the upper-layer txn service perceives the disconnection and reconnects to the newly pulled TN Pod until CN actively disconnects the TCP connection. 

There are 2 possible optimizations:

1. add connection liveness check at the application layer;
2. reduce the liveness detection timeout time for failed connections at the TCP layer through keepalive or adjusting sysctl parameters.

IMHO, these potential optimizations should better be considered as new features and the current behavior is expected.

**Comment by aylei** [comment] 2024-10-27 15:35
not a bug

**Comment by aylei** [comment] 2024-10-31 14:34
tracking

**Comment by aylei** [comment] 2024-11-21 02:58
@volgariver6 PTAL

**Comment by volgariver6** [comment] 2024-12-10 03:01
fixed in main

**Comment by aressu1985** [comment] 2024-12-24 03:08
fixed

**Closed by aressu1985** 2024-12-24 03:08 UTC
Labels: kind/tech-request, priority/p0
