### ISSUE TITLE
[Bug]: In-correct data in the statement_info(duplicate/missing statement/incorrect user) and data racing

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#12432] opened 2023-10-31 00:42 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-9be61237
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
MySQL [mo_cloud]> select statement_id,status,statement,request_at,response_at from system.statement_info where statement_id = '8e28a8c7-73de-11ee-ac72-1a400f922fd4';
+--------------------------------------+---------+-----------------------------------------------------------------------------------------------------------------+----------------------------+----------------------------+
| statement_id                         | status  | statement                                                                                                       | request_at                 | response_at                |
+--------------------------------------+---------+-----------------------------------------------------------------------------------------------------------------+----------------------------+----------------------------+
| 8e28a8c7-73de-11ee-ac72-1a400f922fd4 | Success | prepare __mo_stmt_id_4687 from UPDATE device_info_2 SET heartbeat_time=?, status=? WHERE (physical_device_id=?) | 2023-10-26 09:03:40.002681 | 2023-10-26 09:03:40.004009 |
| 8e28a8c7-73de-11ee-ac72-1a400f922fd4 | Success | prepare __mo_stmt_id_4687 from UPDATE device_info_2 SET heartbeat_time=?, status=? WHERE (physical_device_id=?) | 2023-10-26 09:03:40.002681 | 2023-10-26 09:03:40.004009 |
+--------------------------------------+---------+-----------------------------------------------------------------------------------------------------------------+----------------------------+----------------------------+
2 rows in set (39.37 sec)
```

### Expected Behavior

Only 1 success or failed statement record for 1 query

### Steps to Reproduce

```Markdown
NA
```

### Additional information

Check this in the freetier-01 cluster

related issue https://github.com/matrixorigin/matrixone/issues/12571 https://github.com/matrixorigin/matrixone/issues/10382 https://github.com/matrixorigin/matrixone/issues/10378 https://github.com/matrixorigin/matrixone/issues/10551

**Comment by gavinyue** [comment] 2023-11-01 15:19
The first PR has been merged

**Comment by DanielZhangQD** [comment] 2023-11-02 01:22
The issue remains after upgrade:
```
MySQL [mobug]> select statement_id, count(*) cnt, min(response_at) minrsp, max(response_at) maxrsp from system.statement_info where response_at >= '2023-11-01 09:00:40.004009' and response_at < '2023-11-02 02:13:40.004009' group by statement_id order by cnt desc limit 10;
+--------------------------------------+------+----------------------------+----------------------------+
| statement_id                         | cnt  | minrsp                     | maxrsp                     |
+--------------------------------------+------+----------------------------+----------------------------+
| 99b384f9-78a7-11ee-9e07-1e58b4dc8f3c |    2 | 2023-11-01 11:12:52.862274 | 2023-11-01 11:12:52.862274 |
| 99a0eb3a-78a7-11ee-9e07-1e58b4dc8f3c |    2 | 2023-11-01 11:12:52.739586 | 2023-11-01 11:12:52.739586 |
| 99a61a29-78a7-11ee-9e07-1e58b4dc8f3c |    2 | 2023-11-01 11:12:52.773560 | 2023-11-01 11:12:52.773560 |
| 99ad2e86-78a7-11ee-9e07-1e58b4dc8f3c |    2 | 2023-11-01 11:12:52.819951 | 2023-11-01 11:12:52.819951 |
| 99b15c83-78a7-11ee-9e07-1e58b4dc8f3c |    2 | 2023-11-01 11:12:52.848215 | 2023-11-01 11:12:52.848215 |
| 999d7c8f-78a7-11ee-9e07-1e58b4dc8f3c |    2 | 2023-11-01 11:12:52.717876 | 2023-11-01 11:12:52.717876 |
| 999d8182-78a7-11ee-9e07-1e58b4dc8f3c |    2 | 2023-11-01 11:12:52.718368 | 2023-11-01 11:12:52.718368 |
| 99a549b5-78a7-11ee-9e07-1e58b4dc8f3c |    2 | 2023-11-01 11:12:52.768220 | 2023-11-01 11:12:52.768220 |
| 99b50161-78a7-11ee-9e07-1e58b4dc8f3c |    2 | 2023-11-01 11:12:52.871967 | 2023-11-01 11:12:52.871967 |
| 99ac1436-78a7-11ee-9e07-1e58b4dc8f3c |    2 | 2023-11-01 11:12:52.812724 | 2023-11-01 11:12:52.812724 |
+--------------------------------------+------+----------------------------+----------------------------+
10 rows in set (18.29 sec)
```

**Comment by gavinyue** [comment] 2023-11-03 14:12
Working on it

**Comment by gavinyue** [comment] 2023-11-06 17:24
https://github.com/matrixorigin/matrixone/pull/12496 

one PR for solving this issue

**Comment by DanielZhangQD** [comment] 2023-11-08 07:27
Two records for the same sql but with different stats:
```
+--------------------------------------+-----------------------------+----------+-------------------+--------------------------------------+---------+----------------------------+
| statement_id                         | stats                       | duration | sql_source_type   | account                              | status  | response_at                |
+--------------------------------------+-----------------------------+----------+-------------------+--------------------------------------+---------+----------------------------+
| e9041fe9-7e00-11ee-8b53-8a88637d4de5 | [3,26374,25370.000,0,0,0,2] |   567638 | cloud_nonuser_sql | 509649f6_8622_4777_ae4c_3819cd8d77bd | Success | 2023-11-08 06:34:44.139987 |
| e9041fe9-7e00-11ee-8b53-8a88637d4de5 | [3,52748,50740.000,0,0,0,2] |   567638 | cloud_nonuser_sql | 509649f6_8622_4777_ae4c_3819cd8d77bd | Success | 2023-11-08 06:34:44.139987 |
+--------------------------------------+-----------------------------+----------+-------------------+--------------------------------------+---------+----------------------------+
2 rows in set (42.48 sec)
```

**Comment by DanielZhangQD** [comment] 2023-11-08 07:34
```
MySQL [mo_cloud]> select * from system.statement_info where  response_at >= '2023-11-08 06:34:00.000' and response_at <= '2023-11-08 06:35:00.000' and statement_id = 'e9041fe9-7e00-11ee-8b53-8a88637d4de5';
+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+-------+--------------------+----------+-----------+---------------+-----------------------+--------------------------------------+-----------+----------------------------+----------------------------+----------+---------+----------+-------+--------------------------------------------------------------------------------------------------------------------------------------+-----------+------------+-----------------------------+----------------+------------+---------+-------------------+------------+--------------+
| statement_id                         | transaction_id                       | session_id                           | account                              | user  | host               | database | statement | statement_tag | statement_fingerprint | node_uuid                            | node_type | request_at                 | response_at                | duration | status  | err_code | error | exec_plan                                                                                                                            | rows_read | bytes_scan | stats                       | statement_type | query_type | role_id | sql_source_type   | aggr_count | result_count |
+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+-------+--------------------+----------+-----------+---------------+-----------------------+--------------------------------------+-----------+----------------------------+----------------------------+----------+---------+----------+-------+--------------------------------------------------------------------------------------------------------------------------------------+-----------+------------+-----------------------------+----------------+------------+---------+-------------------+------------+--------------+
| e9041fe9-7e00-11ee-8b53-8a88637d4de5 | 81a55d91-2690-4992-a29b-7c4bc467e1dd | f85894fa-7dfd-11ee-8b53-8a88637d4de5 | 509649f6_8622_4777_ae4c_3819cd8d77bd | admin | 172.20.5.132:54840 | tpcc     | use tpcc  |               |                       | 38386635-3766-6539-3465-326438633861 | CN        | 2023-11-08 06:34:46.952527 | 2023-11-08 06:34:44.139987 |   567638 | Success | 0        |       | {"steps":null,"code":200,"message":"sql query ignore execution plan","success":false,"uuid":"e756e0f6-7e00-11ee-8b53-8a88637d4de5"}
 |       418 |      24645 | [3,26374,25370.000,0,0,0,2] | Use            | Other      |       2 | cloud_nonuser_sql |          0 |            0 |
| e9041fe9-7e00-11ee-8b53-8a88637d4de5 | 81a55d91-2690-4992-a29b-7c4bc467e1dd | f85894fa-7dfd-11ee-8b53-8a88637d4de5 | 509649f6_8622_4777_ae4c_3819cd8d77bd | admin | 172.20.5.132:54840 | tpcc     | use tpcc  |               |                       | 38386635-3766-6539-3465-326438633861 | CN        | 2023-11-08 06:34:46.952527 | 2023-11-08 06:34:44.139987 |   567638 | Success | 0        |       | {"steps":null,"code":200,"message":"sql query ignore execution plan","success":false,"uuid":"e756e0f6-7e00-11ee-8b53-8a88637d4de5"}
 |       418 |      24645 | [3,52748,50740.000,0,0,0,2] | Use            | Other      |       2 | cloud_nonuser_sql |          0 |            0 |
+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+-------+--------------------+----------+-----------+---------------+-----------------------+--------------------------------------+-----------+----------------------------+----------------------------+----------+---------+----------+-------+--------------------------------------------------------------------------------------------------------------------------------------+-----------+------------+-----------------------------+----------------+------------+---------+-------------------+------------+--------------+
2 rows in set (3 min 59.40 sec)
```

**Comment by xzxiong** [comment] 2023-11-08 10:56
> ```
> MySQL [mo_cloud]> select * from system.statement_info where  response_at >= '2023-11-08 06:34:00.000' and response_at <= '2023-11-08 06:35:00.000' and statement_id = 'e9041fe9-7e00-11ee-8b53-8a88637d4de5';
> +--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+-------+--------------------+----------+-----------+---------------+-----------------------+--------------------------------------+-----------+----------------------------+----------------------------+----------+---------+----------+-------+--------------------------------------------------------------------------------------------------------------------------------------+-----------+------------+-----------------------------+----------------+------------+---------+-------------------+------------+--------------+
> | statement_id                         | transaction_id                       | session_id                           | account                              | user  | host               | database | statement | statement_tag | statement_fingerprint | node_uuid                            | node_type | request_at                 | response_at                | duration | status  | err_code | error | exec_plan                                                                                                                            | rows_read | bytes_scan | stats                       | statement_type | query_type | role_id | sql_source_type   | aggr_count | result_count |
> +--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+-------+--------------------+----------+-----------+---------------+-----------------------+--------------------------------------+-----------+----------------------------+----------------------------+----------+---------+----------+-------+--------------------------------------------------------------------------------------------------------------------------------------+-----------+------------+-----------------------------+----------------+------------+---------+-------------------+------------+--------------+
> | e9041fe9-7e00-11ee-8b53-8a88637d4de5 | 81a55d91-2690-4992-a29b-7c4bc467e1dd | f85894fa-7dfd-11ee-8b53-8a88637d4de5 | 509649f6_8622_4777_ae4c_3819cd8d77bd | admin | 172.20.5.132:54840 | tpcc     | use tpcc  |               |                       | 38386635-3766-6539-3465-326438633861 | CN        | 2023-11-08 06:34:46.952527 | 2023-11-08 06:34:44.139987 |   567638 | Success | 0        |       | {"steps":null,"code":200,"message":"sql query ignore execution plan","success":false,"uuid":"e756e0f6-7e00-11ee-8b53-8a88637d4de5"}
>  |       418 |      24645 | [3,26374,25370.000,0,0,0,2] | Use            | Other      |       2 | cloud_nonuser_sql |          0 |            0 |
> | e9041fe9-7e00-11ee-8b53-8a88637d4de5 | 81a55d91-2690-4992-a29b-7c4bc467e1dd | f85894fa-7dfd-11ee-8b53-8a88637d4de5 | 509649f6_8622_4777_ae4c_3819cd8d77bd | admin | 172.20.5.132:54840 | tpcc     | use tpcc  |               |                       | 38386635-3766-6539-3465-326438633861 | CN        | 2023-11-08 06:34:46.952527 | 2023-11-08 06:34:44.139987 |   567638 | Success | 0        |       | {"steps":null,"code":200,"message":"sql query ignore execution plan","success":false,"uuid":"e756e0f6-7e00-11ee-8b53-8a88637d4de5"}
>  |       418 |      24645 | [3,52748,50740.000,0,0,0,2] | Use            | Other      |       2 | cloud_nonuser_sql |          0 |            0 |
> +--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+-------+--------------------+----------+-----------+---------------+-----------------------+--------------------------------------+-----------+----------------------------+----------------------------+----------+---------+----------+-------+--------------------------------------------------------------------------------------------------------------------------------------+-----------+------------+-----------------------------+----------------+------------+---------+-------------------+------------+--------------+
> 2 rows in set (3 min 59.40 sec)
> ```

这个 case ，stats 的数值刚好差了 一倍；
说明了 StatementInfo 被 2次塞到 buffer 中，触发了两次调用 `ExecPlan2Stats`，导致了输出了两次。
所以，应该不是 ETLMerge 导致的两次。

**Comment by DanielZhangQD** [comment] 2023-11-08 12:57
```
| 4f692b2d-7e02-11ee-8b53-8a88637d4de5 | [3,11209,30277.000,0,0,0,2]               |     309423 | cloud_nonuser_sql | 509649f6_8622_4777_ae4c_3819cd8d77bd | 2023-11-08 06:44:48.237151 |
| 4f692b2d-7e02-11ee-8b53-8a88637d4de5 | [3,33627,90831.000,0,0,0,2]               |     309423 | cloud_nonuser_sql | 509649f6_8622_4777_ae4c_3819cd8d77bd | 2023-11-08 06:44:48.237151 |
| 4f692b2d-7e02-11ee-8b53-8a88637d4de5 | [3,44836,121108.000,0,0,0,2]              |     309423 | cloud_nonuser_sql | 509649f6_8622_4777_ae4c_3819cd8d77bd | 2023-11-08 06:44:48.237151 |
| 4f692b2d-7e02-11ee-8b53-8a88637d4de5 | [3,22418,60554.000,0,0,0,2]               |     309423 | cloud_nonuser_sql | 509649f6_8622_4777_ae4c_3819cd8d77bd | 2023-11-08 06:44:48.237151 |
```

**Comment by xzxiong** [comment] 2023-11-09 03:44
现象：
1.  request_at > response_at
分析
1. 该对象很可能在被free 之前，就被复用了。
```
select statement_id, node_uuid, request_at, response_at, aggr_count from system.statement_info where  request_at between '2023-11-08 06:43:49' and '2023-11-08 06:44:49' and statement_id = '2cf9db0f-7e02-11ee-bbff-b6dc862f9950' ;
```
![image](https://github.com/matrixorigin/matrixone/assets/3927687/ac57db9e-baf6-4b17-bf5a-0440142e6964)

**Comment by gavinyue** [comment] 2023-11-09 04:30
SELECT statement, stats FROM `system`.statement_info where statement_id  = '2c43bea0-7e02-11ee-bbff-b6dc862f9950';

`mysql> SELECT statement, stats FROM `system`.statement_info where statement_id  = '2c43bea0-7e02-11ee-bbff-b6dc862f9950';
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------+
| statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | stats                       |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------+
| /* 1 queries */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | [3,16716,35733.000,0,0,0,0] |
| /* 1 queries */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | [3,16716,35733.000,0,0,0,0] |
| /* 1 queries */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | [3,16716,35733.000,0,0,0,0] |
| /* 1 queries */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | [3,16716,35733.000,0,0,0,0] |
| /* 1 queries */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | [3,16716,35733.000,0,0,0,0] |
| /* 1 queries */
select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys"select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys"select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys"select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys"select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys"select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys"select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys" | [3,16716,35733.000,0,0,0,0] |
| /* 1 queries */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | [3,16716,35733.000,0,0,0,0] |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------+`

**Comment by gavinyue** [comment] 2023-11-09 04:36
上面这个statement, 被写了七遍， 而且有一条的statement 还和其他的不一样


| /* 1 queries */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| /* 1 queries */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| /* 1 queries */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| /* 1 queries */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| /* 1 queries */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| /* 1 queries */
select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys"select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys"select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys"select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys"select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys"select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys"select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys" |
| /* 1 queries */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
7 rows in set (1 min 44.51 sec

**Comment by gavinyue** [comment] 2023-11-09 07:57
https://github.com/matrixorigin/matrixone/pull/12619

Try to solve the racing problem

**Comment by gavinyue** [comment] 2023-11-11 05:57
related issue #12571 #10382 #10378 #10551 

基本都是写入的问题， racing导致的duplicate 和 数据内容问题。  正在本地测试，都很难复现问题

**Comment by gavinyue** [comment] 2023-11-14 16:11
忘记回复了，昨天来回测了半天，加了mutex 只能说同一个不再复写了，但是没找到为什么会有复用的问题。

**Comment by gavinyue** [comment] 2023-11-16 07:01
今天还是没找到问题。  明天继续

**Comment by gavinyue** [comment] 2023-11-17 15:53
Pending

**Comment by gavinyue** [comment] 2023-11-20 04:25
还在处理

**Comment by gavinyue** [comment] 2023-11-21 15:07
正在处理中

**Comment by gavinyue** [comment] 2023-11-22 13:02
今天继续

**Comment by gavinyue** [comment] 2023-11-23 10:24
还没发现原因

**Comment by gavinyue** [comment] 2023-11-25 08:50
继续研究中...

**Comment by gavinyue** [comment] 2023-11-30 14:37
Working

**Comment by gavinyue** [comment] 2023-12-08 05:29
![image](https://github.com/matrixorigin/matrixone/assets/54566980/ecb9bddf-b6f3-4264-8965-c9591427ecc8)

**Comment by gavinyue** [comment] 2023-12-08 05:30
cloud 似乎没有duplicate了

**Comment by gavinyue** [comment] 2023-12-08 05:40
12/4号以后又出现了。。。
![Screenshot 2023-12-07 at 9 37 57 PM](https://github.com/matrixorigin/matrixone/assets/54566980/0cb92bbc-1432-4722-9cf5-3c9f0e3a1bb0)

**Comment by gavinyue** [comment] 2023-12-08 06:25
related:

https://github.com/matrixorigin/matrixone/issues/12571
https://github.com/matrixorigin/matrixone/issues/10551

**Comment by gavinyue** [comment] 2023-12-08 06:43
https://github.com/matrixorigin/matrixone/pull/12619

等这个merge了，  可以考虑挪到1.2 继续观察验证。

**Comment by gavinyue** [comment] 2023-12-12 04:00
已经merge https://github.com/matrixorigin/matrixone/pull/12619

**Comment by DanielZhangQD** [comment] 2023-12-13 02:50
Two statements with the same statement_id but different response_at:
```
select statement_id,stats,response_at from system.statement_info where statement_id = 'b92b7375-9955-11ee-ade0-2e67831535c5' and response_at >= '2023-12-13 01:19:00.000' and response_at < '2023-12-13 01:21:00.000';
+--------------------------------------+--------------------------------------+----------------------------+
| statement_id                         | stats                                | response_at                |
+--------------------------------------+--------------------------------------+----------------------------+
| b92b7375-9955-11ee-ade0-2e67831535c5 | [3,378238,2238.000,0,0,189,2]        | 2023-12-13 01:19:57.681341 |
| b92b7375-9955-11ee-ade0-2e67831535c5 | [3,26754532,8385262.067,0,0,10725,2] | 2023-12-13 01:20:00.000000 |
+--------------------------------------+--------------------------------------+----------------------------+
2 rows in set (0.04 sec)
```

**Comment by gavinyue** [comment] 2023-12-16 01:58
1.0.1 似乎又好转

**Comment by gavinyue** [comment] 2023-12-21 11:15
Pending

**Comment by gavinyue** [comment] 2023-12-27 14:09
Pending

**Comment by gavinyue** [comment] 2024-01-04 13:28
Pending

**Comment by gavinyue** [comment] 2024-01-10 15:08
Pending

**Comment by gavinyue** [comment] 2024-01-15 11:48
Pending

**Comment by DanielZhangQD** [comment] 2024-01-18 07:04
Reproduced in cloud qa env, 1.1-dev
```
MySQL [mo_cloud]> select statement_id,request_at,response_at,stats,duration from system.statement_info where statement_id = 'dae73140-b5b0-11ee-a8aa-86b79c86c056' and request_at >= '2024-01-18 03:00:00.000';
+--------------------------------------+----------------------------+----------------------------+----------------------------------+----------+
| statement_id                         | request_at                 | response_at                | stats                            | duration |
+--------------------------------------+----------------------------+----------------------------+----------------------------------+----------+
| dae73140-b5b0-11ee-a8aa-86b79c86c056 | 2024-01-18 03:22:50.000000 | 2024-01-18 03:22:55.000000 | [3,7301105,233332.483,0,0,278,2] | 10315601 |
| dae73140-b5b0-11ee-a8aa-86b79c86c056 | 2024-01-18 03:22:50.000000 | 2024-01-18 03:22:55.000000 | [3,7301105,233332.483,0,0,278,2] | 10315601 |
| dae73140-b5b0-11ee-a8aa-86b79c86c056 | 2024-01-18 03:22:55.000000 | 2024-01-18 03:23:00.000000 | [3,7301105,468432.000,0,0,278,2] | 10315601 |
+--------------------------------------+----------------------------+----------------------------+----------------------------------+----------+
3 rows in set (0.00 sec)
```

**Comment by xzxiong** [comment] 2024-01-23 10:15
Pending

**Comment by xzxiong** [comment] 2024-01-25 12:30
relate refator #13625

**Comment by xzxiong** [comment] 2024-01-30 10:09
pending

**Comment by xzxiong** [comment] 2024-02-02 10:09
pending

**Comment by xzxiong** [comment] 2024-02-08 02:13
pending

**Comment by xzxiong** [comment] 2024-02-21 10:28
pending

**Comment by xzxiong** [comment] 2024-03-01 10:21
pending

**Comment by xzxiong** [comment] 2024-03-08 01:57
next week start

**Comment by xzxiong** [comment] 2024-03-13 10:12
pending

**Comment by xzxiong** [comment] 2024-03-18 10:15
pending

**Comment by xzxiong** [comment] 2024-03-21 11:05
pending

**Comment by xzxiong** [comment] 2024-03-26 10:12
Pending

**Comment by xzxiong** [comment] 2024-03-29 10:06
Pending

**Comment by xzxiong** [comment] 2024-04-03 10:19
Pending

**Comment by xzxiong** [comment] 2024-04-08 14:16
Pending

**Comment by xzxiong** [comment] 2024-04-11 10:11
Pending

**Comment by xzxiong** [comment] 2024-04-16 10:35
Pending

**Comment by xzxiong** [comment] 2024-04-19 10:19
Pending

**Comment by xzxiong** [comment] 2024-04-24 10:10
Pending

**Comment by xzxiong** [comment] 2024-04-29 10:12
Pending

**Comment by xzxiong** [comment] 2024-05-02 10:59
Pending

**Comment by xzxiong** [comment] 2024-05-07 10:12
Pending

**Comment by xzxiong** [comment] 2024-05-10 10:42
Pending

**Comment by xzxiong** [comment] 2024-05-15 10:18
Pending

**Comment by xzxiong** [comment] 2024-05-20 10:10
Pending

**Comment by xzxiong** [comment] 2024-05-23 12:37
Pending

**Comment by xzxiong** [comment] 2024-05-28 10:13
Pending

**Comment by xzxiong** [comment] 2024-05-31 10:12
Pending

**Comment by xzxiong** [comment] 2024-06-05 10:12
Pending

**Comment by xzxiong** [comment] 2024-06-10 10:16
Pending

**Comment by xzxiong** [comment] 2024-06-18 11:59
Not plan yet

**Comment by xzxiong** [comment] 2024-06-21 10:11
Not plan yet

**Comment by xzxiong** [comment] 2024-06-25 03:57
no repro lately

**Comment by xzxiong** [comment] 2024-06-28 10:10
no repro lately

**Comment by xzxiong** [comment] 2024-07-03 10:20
no repro lately

**Comment by xzxiong** [comment] 2024-07-08 11:05
no repro lately
- root cause: 没有确定真实原因
- 近期改动: 1.2.0 重构了 frontend 对 statement_info 采集的逻辑，去除了在 context 中引用。每个session 保证只持有一个 statement_info。

ref pr: https://github.com/matrixorigin/matrixone/pull/16411

**Comment by aressu1985** [comment] 2024-07-18 02:09
问题单先关闭，等带复现后再重新提

**Closed by aressu1985** 2024-07-18 02:09 UTC
Labels: kind/bug, severity/s0, impact/1.1, phase/testing
