### ISSUE TITLE
[Bug]: The datatime value sometimes has 9 digital scale return by jdbc

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3290] opened 2022-06-23 12:28 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: cases/expression/temporal_interval.sql
[ROW    NUMBER]: 264
[SQL STATEMENT]: select * from t1 where i > 6;
[EXPECT RESULT]:
i       a       b       c       d       e
7       1998-01-01 00:00:00     1998-01-01 00:00:00     1998-01-02 00:00:00     1998-01-01 00:00:00     1997-12-31 23:59:59.000002
8       1998-01-01 00:00:00     1998-01-01 00:00:00     1998-01-02 00:00:00     1998-01-01 00:00:00     1997-12-31 23:59:59.000002
9       1998-01-01 00:00:00     1998-01-01 00:00:00     1998-01-02 00:00:00     1998-01-01 00:00:00     1997-12-31 23:59:59.000002
10      2010-11-12 00:00:00     1998-01-01 00:00:00     1998-01-02 00:00:00     1998-01-01 00:00:00     1997-12-31 23:59:59.000002
11      null    null    null    null    null
[ACTUAL RESULT]:
i       a       b       c       d       e
7       1998-01-01 00:00:00     1998-01-01 00:00:00     1998-01-02 00:00:00.000001000   1998-01-01 00:00:00     1997-12-31 23:59:59.000002
8       1998-01-01 00:00:00     1998-01-01 00:00:00     1998-01-02 00:00:00.000001000   1998-01-01 00:00:00     1997-12-31 23:59:59.000002
9       1998-01-01 00:00:00     1998-01-01 00:00:00     1998-01-02 00:00:00.000001000   1998-01-01 00:00:00     1997-12-31 23:59:59.000002
10      2010-11-12 00:00:00.000014000   1998-01-01 00:00:00     1998-01-02 00:00:00.000001000   1998-01-01 00:00:00     1997-12-31 23:59:59.000002
11      null    null    null    null    null

**Comment by broccoliSpicy** [comment] 2022-06-24 08:37
I believe the behavior is caused by testing tool rather than matrixone

**Comment by daviszhen** [comment] 2022-06-27 04:09
I will verify it today

**Comment by dengn** [comment] 2022-06-30 04:15
JDBC related, to be resolved in 0.6

**Comment by aressu1985** [comment] 2022-12-03 08:43
Will resolve this issue in 0.7.0

**Comment by aressu1985** [comment] 2023-05-20 07:07
not working on it

**Comment by aressu1985** [comment] 2023-07-22 13:25
working on it next week

**Closed** 2023-07-28 10:16 UTC
Labels: kind/bug, triage/accepted, severity/s1, bvt, test-infra
