### ISSUE TITLE
[Bug]: de gob

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#7111] opened 2022-12-09 02:27 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

some of our serial/deserial code use gob.   which is extremely slow and memory intensive.

all our ser/deser should use protocol buf, or maybe we upgrade to flat buffer.

```
ftian@DESKTOP-16FCU43:~/m/matrixone/pkg$ grep -r 'encoding/gob' .
./fileservice/caching_file_service_test.go:     "encoding/gob"
./fileservice/file_service_test.go:     "encoding/gob"
./txn/storage/tae/write.go:     "encoding/gob"
./txn/storage/tae/read.go:      "encoding/gob"
./txn/storage/memorystorage/write.go:   "encoding/gob"
./txn/storage/memorystorage/storage_test.go:    "encoding/gob"
./txn/storage/memorystorage/read.go:    "encoding/gob"
./hakeeper/rsm.go:      "encoding/gob"
./logservice/rsm.go:    "encoding/gob"
./container/types/encoding.go:  "encoding/gob"
./vm/engine/memoryengine/operations_test.go:    "encoding/gob"
./vm/engine/memoryengine/request.go:    "encoding/gob"
./vm/engine/disttae/gob.go:     "encoding/gob"
./vm/engine/tae/db/operations.go:       "encoding/gob"
./vm/engine/gob.go:     "encoding/gob"
./common/moerr/error.go:        "encoding/gob"
```

**Comment by aunjgr** [comment] 2022-12-13 11:11
Need some investigation. Will begin at Thursday/Friday.

**Comment by fengttt** [comment] 2022-12-16 05:14
https://github.com/matrixorigin/matrixone/issues/7092  See this one for profiling.

**Comment by aunjgr** [comment] 2022-12-27 15:22
No progress yet.

**Comment by aunjgr** [comment] 2023-01-03 13:17
Investigating

**Comment by aunjgr** [comment] 2023-01-04 10:00
Some thoughts:

* In general, (de)serialization should be reduced as much as possible
* Some `struct` handled by `gob` are actually defined by `protobuf`. We should try `protobuf`'s serialization firstly. But I don't invest much hope in it.
* If `protobuf` is not much faster than `gob`, we should try other ser/deser schemes, such as https://github.com/fxamacker/cbor

**Comment by aunjgr** [comment] 2023-01-10 11:54
No progress yet. Working on vector refactor.

**Comment by aunjgr** [comment] 2023-01-12 12:12
No progress yet. Working on vector refactor.

**Comment by aunjgr** [comment] 2023-01-17 11:21
Working on subquery issues

**Comment by aunjgr** [comment] 2023-01-20 12:30
No progress

**Comment by aunjgr** [comment] 2023-01-31 13:35
No progress today

**Comment by cnutshell** [comment] 2023-02-07 12:32
Working on generics performance investigation.

**Comment by cnutshell** [comment] 2023-02-12 02:08
I’ll pick it up with higher priority.

**Comment by cnutshell** [comment] 2023-02-16 16:05
Here's [some benchmarks](https://ugorji.net/blog/benchmarking-serialization-in-go) for golang encoding libraries, I'm confirming its description.

**Comment by cnutshell** [comment] 2023-02-19 09:53
> Here's [some benchmarks](https://ugorji.net/blog/benchmarking-serialization-in-go) for golang encoding libraries, I'm confirming its description.

The author designs a structure named `TestStruc ` and tests it with different encoding libraries/formats from the following aspects:
- encoded size
- encoding speed
- decoding speed

It seems that [msgpack](http://github.com/msgpack/msgpack) comes the first on the speed of encoding/decoding. But it shows that msgpack `has very minimal forwards/backwards compatibility support when used with the typed C++ interface` according to [C++ Benchmarks for FlatBuffers](https://google.github.io/flatbuffers/flatbuffers_benchmarks.html).

What we care about is the overhead of encoding/decoding, that depends on the selected encoding format and whether we take advantage of encoding libraries properly or not.

As to golang's standard library `encoding/gob`, calling `gob.NewDecoder / gob.NewEncoder` is a very costly operation, so gob is best used for streaming a lot of data. According to memory profiling of the following benchmark, there are 5 allocs per op.

```go
import (
	"encoding/gob"
	"testing"
)

var global *gob.Encoder

func BenchmarkNewEncoder(b *testing.B) {
	var enc *gob.Encoder
	for i := 0; i < b.N; i++ {
		enc = gob.NewEncoder(&mockWriter{})
	}
	global = enc
}

type mockWriter struct{}

func (w *mockWriter) Write(p []byte) (n int, err error) {
	return 0, nil
}
```

**Comment by cnutshell** [comment] 2023-02-20 03:19
Protocol Buffers and FlatBuffers are alternatives for golang's standard gob encoding format.

The key difference is that **FlatBuffers doesn't de-serialize at all**, ever. It allows you to access the serialized data in-place.
FlatBuffers was designed for use cases where memory usage and speed matter. But the wire format of FlatBuffers is not as compact as Protocol Buffers.

I will replace `encoding/gob` with Protocol Buffers first. Then Flatbuffers if necessary. Just take [badger](https://github.com/dgraph-io/badger) as an example, it uses Flatbuffers instead of Protocol buffers for [table index](https://github.com/dgraph-io/badger/blob/main/fb/flatbuffer.fbs) and directly stores byte slices in the cache.

**Comment by cnutshell** [comment] 2023-02-22 12:06
Could we marshal golang's struct to Protocol Buffers directly? Or is a`.proto` file necessary?

Until commit `efeca9a` of package [github.com/golang/protobuf](https://github.com/golang/protobuf), `proto.Marshal` accept a parameter of type `interface{}`. It seems that we could marshal golang's struct without a `.proto`. But the commit was long long ago, maybe it's a waste of time to find a way.

Working on another issue concurrently.

So the plan is to define related struct within a `.proto` file, then replace the gob encoding code.

**Comment by cnutshell** [comment] 2023-02-24 14:07
I took a look at memory leak related issues.

**Comment by cnutshell** [comment] 2023-02-26 12:53
After profiling a select execution base on tpch 30G, I'm afraid that getting rid of gob encoding wouldn't contribute too much for performance improvement.

**Comment by cnutshell** [comment] 2023-02-28 02:38
It's really a huge task, because:
- All related `golang structs` should be translated as `proto` definition, and some structs are nested
- In the current implementation, `gob encoding` is widely used in order to transfer byte slice payload between `cn service` and `dn service`

**Comment by fengttt** [comment] 2023-03-01 04:54
I don't get it.   Why is it hard?   The worst case is that you find all gob in our code, grep -ri gob, and remove all code then serialize it manually.

**Comment by cnutshell** [comment] 2023-03-01 10:29
> ./fileservice/caching_file_service_test.go:     "encoding/gob"
> ./fileservice/file_service_test.go:     "encoding/gob"

Because of that:
- All related `golang structs` should be translated as `proto` definition, and some structs are nested
- In the current implementation, `gob encoding` is widely used in order to transfer byte slice payload between `cn service` and `dn service`

**Comment by cnutshell** [comment] 2023-03-02 08:18
```txt
2023-03-02T08:04:24.6253535Z === RUN   TestMemHandler
2023-03-02T08:04:24.6253986Z --- FAIL: TestMemHandler (0.00s)
2023-03-02T08:04:24.6254602Z panic: reflect.Set: value of type map[string]interface {} is not assignable to type engine.TableDef [recovered]
2023-03-02T08:04:24.6255369Z 	panic: reflect.Set: value of type map[string]interface {} is not assignable to type engine.TableDef
2023-03-02T08:04:24.6255740Z 
```

In PR #8225, I try to replace `encoding/gob` with `msgpack`, but failed.
`msgpack` is not allowed in our code space, so I won't spend time to make #8225 through.
Now, there's only one approach, that is PB. Hope me can finish it, good luck!

**Comment by cnutshell** [comment] 2023-03-05 00:51
Working on logtail push model.

**Comment by cnutshell** [comment] 2023-03-07 12:10
Working on logtail push model.

**Comment by cnutshell** [comment] 2023-03-07 13:49
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/20291742/223440010-f14e708e-fe53-477b-a79d-aab3287b9dca.png">

Make a CPU profiling, there are two span related with `encoding/gob`:
- types.Encode contributes 1.23%
- gob.Decode under tae.handleWrite contributes 3.83%

> mo-sysbench oltp_insert test against logtail push model
> commit: 867dba572d9dd6e4253e781116ac8aea4ec58c43

**Comment by cnutshell** [comment] 2023-03-07 13:51
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/20291742/223440010-f14e708e-fe53-477b-a79d-aab3287b9dca.png">

Make a CPU profiling, there are two span related with `encoding/gob`:
- types.Encode contributes 1.23%
- gob.Decode under tae.handleWrite contributes 3.83%

> mo-sysbench oltp_insert test against logtail push model
> commit: 867dba572d9dd6e4253e781116ac8aea4ec58c43

**Comment by cnutshell** [comment] 2023-03-09 15:29
Debug on logtail push model.

**Comment by cnutshell** [comment] 2023-03-11 04:23
Debug on logtail push model.

**Comment by XuPeng-SH** [comment] 2023-03-13 15:13
@cnutshell is working on it this week

**Comment by cnutshell** [comment] 2023-03-14 10:50
Working on my local environment.

**Comment by cnutshell** [comment] 2023-03-16 08:43
Working on my local environment.

**Comment by cnutshell** [comment] 2023-03-19 12:59
Working on my local environment.

**Comment by cnutshell** [comment] 2023-03-23 01:27
Really a daunting work.

**Comment by cnutshell** [comment] 2023-03-24 07:48
With PR #8645, unit tests are all passed, but failed with BVT.
Close it and continue.

**Comment by cnutshell** [comment] 2023-03-26 12:56
Trying to figure out the root cause for failed BVT test.

**Comment by cnutshell** [comment] 2023-03-26 12:57
Delayed, maybe I should take an easier way in order to get rid of gob.

**Comment by cnutshell** [comment] 2023-04-02 14:18
Finally, PB wouldn't satisfy all the `encoding/gob` use cases `matrixone`. I'll end this task next week.

**Comment by cnutshell** [comment] 2023-04-08 10:48
I'm trying to make all the test pass through.

**Comment by cnutshell** [comment] 2023-04-14 04:08
Working on it still.

**Comment by cnutshell** [comment] 2023-04-17 00:45
Try to fix a bug from replacing.

**Comment by cnutshell** [comment] 2023-04-21 00:04
Debuging.

**Comment by cnutshell** [comment] 2023-04-22 10:23
Bug fixed and all bvt tests passed.

**Comment by cnutshell** [comment] 2023-04-23 06:55
the sysbench result shows that there would be some improvements with PR #9123:
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/20291742/233824726-4d83cb7e-b3af-40f5-a7ae-cd6f7e3cd57c.png">

Test on my local environment:
> OS: 5.10.102.1-microsoft-standard-WSL2
> CPU: 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
> Memory: 16GB

**Comment by cnutshell** [comment] 2023-04-25 06:41
Wait PR #9123 merged.

**Closed** 2023-04-26 05:27 UTC
Labels: kind/bug, priority/p0, needs-triage, severity/s0, perf-tp
