### ISSUE TITLE
[Bug]: The following script shows many bugs

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#8530] opened 2023-03-19 08:36 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others: launch multi cn
```

### Actual Behavior

The included scripts may,

- crash the server
- fail with message too long
- fail with wrong number of rows

### Expected Behavior

Last select count(*) should return 33554432

### Steps to Reproduce

```Markdown
use ftian;

drop table if exists bugt;
create table bugt (i int, j int, k int, s varchar(100));
insert into bugt values (1, 1, 1, 'foobarzoo okok foo bar zoo');

begin;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
commit;

begin;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
commit;

begin;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
commit;

begin;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
commit;

begin;
select 'here';
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
insert into bugt select * from bugt;
select count(*) from bugt;
commit;
```

**Comment by fengttt** [comment] 2023-03-19 08:39
May be the same issue as #7748

**Comment by m-schen** [comment] 2023-03-20 12:03
I have fixed this bug. and `fail with message too long` still exists.
I will keep on tracing.

**Comment by m-schen** [comment] 2023-03-21 12:07
Sorry.
The previous comment was incorrect, the bug with the error result was not resolved. 
When executing this statement with a repro script, an incomprehensible large number of counts would appear.
<img width="514" alt="image" src="https://user-images.githubusercontent.com/59043531/226601371-1e8e4432-6671-44ef-910d-c2d68e3c0448.png">

**Comment by m-schen** [comment] 2023-03-22 13:26
今天没有看这个，在看7748

**Comment by m-schen** [comment] 2023-03-23 12:11
https://github.com/matrixorigin/matrixone/pull/8643

**Comment by m-schen** [comment] 2023-03-24 11:27
等#8643和#8667合并

**Comment by arjunsk** [comment] 2023-03-27 04:28
I think this issue is still reproducible.

Fails in "DN vector refactor branch": https://github.com/matrixorigin/matrixone/actions/runs/4525622050/jobs/7974782383

![image](https://user-images.githubusercontent.com/9638314/227840638-5d41f2b8-854f-4883-8ab8-1d041e33cf93.png)

**Comment by m-schen** [comment] 2023-03-27 06:42
The reason for count(*) returning the error result is that the execution of insert failed.
I have download the log.

@arjunsk 
thanks, I have reproduced it locally. I will keep tracing this bug.

**Comment by m-schen** [comment] 2023-03-27 07:05
the pr #8643 fix a write s3 bug, but make it so slow. it may cost more than 60s sometimes now.
The performance needs optimize. 

You can just rerun it.  @arjunsk 
This is not a correctness related bug. Of course, it's not your branch that caused the bug.

**Comment by arjunsk** [comment] 2023-03-27 07:07
Got it. Thank you for the update @m-schen

**Comment by m-schen** [comment] 2023-03-27 08:46
I create a new issue to trace the pool performance #8717 

and this issue has been fixed. can verify can close it at branch main.

**Closed** 2023-03-28 17:02 UTC
Labels: kind/bug, severity/s-1
