### ISSUE TITLE
[Bug]: bvt failed because of wrong resultset of `select from mo_catalog.mo_role_grant, mo_catalog.mo_role, mo_catalog.mo_role_privs,`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#7007] opened 2022-11-30 02:14 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 565670b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

This error occurred during a BVT running with race enabled; all details can be found here: https://github.com/matrixorigin/matrixone/actions/runs/3571068071/jobs/6002615202

```
[ERROR]
[SCRIPT   FILE]: /home/runner/work/matrixone/matrixone/head/test/distributed/cases/zz_accesscontrol/grant_privs_role.sql
[ROW    NUMBER]: 265
[SQL STATEMENT]: select mr.role_name,mp.role_name,obj_type,privilege_name,privilege_level from mo_catalog.mo_role_grant mg,mo_catalog.mo_role mr ,mo_catalog.mo_role_privs mp where  mg.grantee_id=mr.role_id and mg.granted_id = mp.role_id and mr.role_name in ('r6','r7');
[EXPECT RESULT]:
role_name    role_name    obj_type    privilege_name    privilege_level
r6    r1    database    create table    *.*
r7    r1    database    create table    *.*
r6    r2    database    create table    *.*
r7    r2    database    create table    *.*
r6    r1    table    select    *.*
r7    r1    table    select    *.*
r6    r2    table    select    *.*
r7    r2    table    select    *.*
r6    r1    table    insert    *.*
r7    r1    table    insert    *.*
r6    r2    table    insert    *.*
r7    r2    table    insert    *.*
r6    r1    table    update    *.*
r7    r1    table    update    *.*
r6    r2    table    update    *.*
r7    r2    table    update    *.*
[ACTUAL RESULT]:
role_name    role_name    obj_type    privilege_name    privilege_level
r6    r1    database    create table    *.*
r7    r1    database    create table    *.*
r6    r2    database    create table    *.*
r7    r2    database    create table    *.*
r6    r1    table    select    *.*
r7    r1    table    select    *.*
r6    r2    table    select    *.*
r7    r2    table    select    *.*
r6    r1    table    insert    *.*
r7    r1    table    insert    *.*
r6    r2    table    insert    *.*
r7    r2    table    insert    *.*
r6    r1    table    update    *.*
r7    r1    table    update    *.*
r6    r2    table    update    *.*
r7    r2    table    update    *.*
r6    r1    database    create table    *.*
r7    r1    database    create table    *.*
r6    r1    table    select    *.*
r7    r1    table    select    *.*
r6    r2    table    select    *.*
r7    r2    table    select    *.*
r6    r1    table    insert    *.*
r7    r1    table    insert    *.*
r6    r2    table    insert    *.*
r7    r2    table    insert    *.*
r6    r1    table    update    *.*
r7    r1    table    update    *.*
r6    r2    table    update    *.*
r7    r2    table    update    *.*
```

**Comment by sukki37** [comment] 2022-12-01 02:44
repro： https://github.com/matrixorigin/matrixone/actions/runs/3580734977/jobs/6023107175

**Comment by triump2020** [comment] 2022-12-03 06:36
After  fixing #6824 ,  i will work on this.

**Comment by XuPeng-SH** [comment] 2022-12-05 14:25
@triump2020 will investigate this issue later

**Comment by triump2020** [comment] 2022-12-06 06:34
After communication with @aressu1985 ,  downgrade to s1

**Comment by triump2020** [comment] 2022-12-07 14:31
no progress

**Comment by triump2020** [comment] 2022-12-07 15:00
> repro： https://github.com/matrixorigin/matrixone/actions/runs/3580734977/jobs/6023107175

/home/runner/work/matrixone/matrixone/head/test/distributed/cases/zz_accesscontrol/create_user.sql] SQL: select user_name, authentication_string from mo_catalog.mo_user where user_name in('c_user_01','c_user_02','c_user_03');

**Comment by sukki37** [comment] 2022-12-08 05:21
repro： https://github.com/matrixorigin/matrixone/actions/runs/3635410793/jobs/6134483585

**Comment by sukki37** [comment] 2022-12-08 08:14
repro：https://github.com/matrixorigin/matrixone/actions/runs/3645735450/jobs/6156142744

**Comment by aptend** [comment] 2022-12-09 10:20
i have saved the log and i will check them later

**Comment by aptend** [comment] 2022-12-12 11:20
have no time today

**Comment by aptend** [comment] 2022-12-14 10:09
the logs are only error level, no valuable information found. I am trying to repro locally

**Comment by aptend** [comment] 2022-12-16 08:12
```txt
2022-12-16 15:38:33 ERROR RSSet:140 - The row count does not equal with each other, one is 8, the other is 4
2022-12-16 15:38:33 ERROR Executor:136 - [/home/foz/repo/matrixone/test/distributed/cases/zz_accesscontrol/drop_user.sql][row:27][select user_name,authentication_string from mo_catalog.mo_user where user_name like 'drop_user_%';] was executed failed, con[id=0, user=dump, pwd=111].
2022-12-16 15:38:33 ERROR Executor:138 - [EXPECT RESULT]:
user_name    authentication_string
drop_user_3    12345678
drop_user_4    12345678
drop_user_5    12345678
drop_user_6    12345678
drop_user_7    12345678
drop_user_8    12345678
drop_user_9    12345678
drop_user_10    12345678
2022-12-16 15:38:33 ERROR Executor:139 - [ACTUAL RESULT]:
user_name    authentication_string
drop_user_7    12345678
drop_user_8    12345678
drop_user_9    12345678
drop_user_10    12345678
```

I ran into this error, but I'm not sure if this problem is the same as the previous ones, for example, https://github.com/matrixorigin/matrixone/actions/runs/3645735450/jobs/6156142744
```txt
2022-12-08 07:03:31 ERROR RSSet:140 - The row count does not equal with each other, one is 3, the other is 0
2022-12-08 07:03:31 ERROR Executor:136 - [/home/runner/work/matrixone/matrixone/head/test/distributed/cases/zz_accesscontrol/grant_privs_role.sql][row:148][select user_name,role_name,obj_type,privilege_name,privilege_level from mo_catalog.mo_user_grant,mo_catalog.mo_user,mo_catalog.mo_role_privs where mo_user_grant.user_id=mo_user.user_id and mo_role_privs.role_id=mo_user_grant.role_id and role_name='role_account_priv_5';] was executed failed, con[id=0, user=dump, ***
2022-12-08 07:03:31 ERROR Executor:138 - [EXPECT RESULT]:
user_name    role_name    obj_type    privilege_name    privilege_level
user_grant_6    role_account_priv_5    database    database ownership    *
user_grant_6    role_account_priv_5    account    create role    *
user_grant_6    role_account_priv_5    account    connect    *
2022-12-08 07:03:31 ERROR Executor:139 - [ACTUAL RESULT]:
user_name    role_name    obj_type    privilege_name    privilege_level
```

anyway, I will try to find the root cause of the repro one

**Comment by aptend** [comment] 2022-12-19 07:39
one case is fixed in https://github.com/matrixorigin/matrixone/pull/7217
before this pr, wrong resultset can be repro by this script
```sql
select mo_ctl('cn', 'task', 'disable');
create database if not exists db;
use db;
create table t (a int);
insert into t values (1), (2), (3), (4), (5);
select mo_ctl('dn', 'flush', 'db.t');
select * from t; -- show 1 2 3 4 5
delete from t where a in (1, 2, 3);

begin;
select mo_ctl('dn', 'flush', 'db.t');
select * from t; -- WRONG!!! show 1 2 3 4 5
commit;
select * from t; -- show 4, 5
```

I am working on another case causing wrong resultset

**Comment by aptend** [comment] 2022-12-21 13:14
fix pr is https://github.com/matrixorigin/matrixone/pull/7283

**Closed** 2023-02-07 13:00 UTC
Labels: kind/bug, severity/s2
