### ISSUE TITLE
[Bug]: huge different in performance between a normal account and a dump account on querying statement_info table

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#6612] opened 2022-11-15 02:55 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 7e5f2f6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1. When we login using custom account, queries on `system.statement_info` usually return less than 1s. However, If I use `sys` account, same query costs more than 10 seconds.
2. it feels like there is no cache, and it still takes that long to execute the second query immediately when I query on `system.statement_info` with `sys` account.

### Steps to Reproduce

```Markdown
1. start a mo cluster in eks, I'm not sure this can be repro in local
2. query, an example query is like `select statement, statement_id, duration, status, request_at, response_at, `user`, `account`, `database`, transaction_id, session_id, rows_read, bytes_scan from statement_info where request_at >= '2022-11-15 00:19:14' and request_at <= '2022-11-15 02:19:14' and account in ('202540ab_3b1b_4192_a4ca_8fb5517d4f06') order by request_at desc limit 0,20;`
```

### Additional information

This environment is still running.

**Comment by qingxinhome** [comment] 2022-11-19 13:46
Problem handling

**Comment by daviszhen** [comment] 2022-11-21 14:31
PR is under reviewing.

**Comment by fengttt** [comment] 2022-11-27 08:15
This should be done via #6436

**Comment by sukki37** [comment] 2022-12-13 13:17
@heni02  will help to verify

**Comment by heni02** [comment] 2022-12-15 09:35
regression commit id :fdf6d0e33d744882b27b348200364db1cab4d465 image:nightly-fdf6d0e, there is a problem #7211 , the new account query  statement_info table and returns 0 rows, I will be verified after the problem is fixed

**Comment by heni02** [comment] 2022-12-16 10:23
Verification next week

**Comment by heni02** [comment] 2022-12-18 02:17
Verification next week

**Comment by heni02** [comment] 2022-12-20 08:20
regression commit id:
sql:select statement_id,transaction_id,session_id,account,statement from system.statement_info where request_at >='2022-12-20 00:39:02.890770' and request_at <='2022-12-20 07:39:02.890770' and account in ('test@123456') order by request_at desc limit 5;
sys account :2.06s
![image](https://user-images.githubusercontent.com/113406637/208616778-1670594b-ba7c-46f6-9eb9-294109e130d7.png)
 non sys account:0.27s
<img width="1439" alt="企业微信截图_9f624007-3b12-4951-9f84-83a384a96290" src="https://user-images.githubusercontent.com/113406637/208617808-b70020bb-ac9b-4125-8f30-5d0f2c46401f.png">

**Comment by florashi181** [comment] 2022-12-30 07:08
@jianwan0214 verify it

**Comment by heni02** [comment] 2023-02-07 11:42
working on tomorrow

**Comment by heni02** [comment] 2023-02-08 03:26
confirm ,closed 
commit id:0ea4925d5cfc6922c8c602c61aa28a83632ca0a7
sql:select statement_id,transaction_id,session_id,account,statement from system.statement_info where request_at >='2023-02-07 00:49:12' and request_at <='2023-02-08 14:49:12' and account in ('account_1') order by request_at desc limit 100;
sys account
![image](https://user-images.githubusercontent.com/113406637/217420323-1fb67fb8-4079-4414-b63a-a98f572b0aaf.png)
![image](https://user-images.githubusercontent.com/113406637/217420964-a1bba0a2-2cd7-4291-85fb-461aaf3258ec.png)

account_1 :
![image](https://user-images.githubusercontent.com/113406637/217420634-2a768a48-5655-41a5-a80f-f14095cfafea.png)
![image](https://user-images.githubusercontent.com/113406637/217420557-b0a262ec-bcf4-402a-b00f-6c52016cdbe4.png)
![image](https://user-images.githubusercontent.com/113406637/217421039-d20225a1-ab04-40c8-acd5-89b11fb69171.png)

**Comment by heni02** [comment] 2023-02-08 08:02
@aressu1985 plz closed this issue

**Closed** 2023-02-08 08:28 UTC
Labels: kind/bug, severity/s0
