### ISSUE TITLE
[Bug]: When using gorm, it was found that there was an issue with the autoincrement column. gorm's' many to many 'cannot be written to data

### ISSUE THREAD

**Issue by xuanyiLee** [matrixorigin/matrixone#12710] opened 2023-11-13 10:12 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id: v1.0.0-rc2
- Go version: 1.20.4
- gorm.io/driver/mysql:  v1.5.2
- gorm.io/gorm:  v1.25.5
```

### Actual Behavior
```go
package main

import (
	"fmt"
	"net/url"
	"strconv"

	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

type User struct {
	gorm.Model
	Name      string
	Languages []Language `gorm:"many2many:user_languages;"`
}

type Language struct {
	gorm.Model
	Name  string
	Users []User `gorm:"many2many:user_languages;"`
}

func getDBConn() *gorm.DB {
	username := "xxx" // modify this
	host := "xxx"           // modify this
	password := "xxx"                                                // modify this
	port := 6001
	database := "test"
	encodedUsername := url.QueryEscape(username)
	dsn := encodedUsername + ":" + password + "@tcp(" + host + ":" + strconv.Itoa(port) + ")/" + database
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{
		// Logger: logger.Default.LogMode(logger.Info), //print SQL
	})
	// get connection
	if err != nil {
		fmt.Println("Database Connection Failed") //Connection failed
	} else {
		fmt.Println("Database Connection Succeed") //Connection succeed
	}
	return db
}

func main() {
	//get *gorm.DB
	db := getDBConn()

	//db.AutoMigrate(&User{})
	//db.AutoMigrate(&Language{})

	user := User{Name: "John"}
	language1 := Language{Name: "English"}
	language2 := Language{Name: "Spanish"}

	db.Create(&user)
	db.Create(&language1)
	db.Create(&language2)

	db.Model(&user).Association("Languages").Append(&language1, &language2)

	db.Save(&user)
}
```
1. run db.AutoMigrate create the table for demo
2. when run the code try to save the data, get a error:
```
2023/11/13 17:56:25 F:/mo-projects/gorm/gorm_create.go:61 Error 20101 (HY000): internal error: Cannot delete or update a parent row: a foreign key const
raint fails
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
[11;1H26ms] [rows:0] INSERT INTO `languages` (`created_at`,`updated_at`,`deleted_at`,`name`,`id`) VALUES ('2023-11-13 09:56:24.564','2023-11-13 09
Process finished with the exit code 011-13 09:56:24.751','2023-11-13 09:56:24.751',NULL,'Spanish',2) ON DUPLICATE KEY UPDATE `id`=`id`

2023/11/13 17:56:25 F:/mo-projects/gorm/gorm_create.go:61 Error 20101 (HY000): internal error: Cannot delete or update a parent row: a foreign key const
raint fails
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted; Error 20101 (HY000): internal error: Cannot delete or update a pa
rent row: a foreign key constraint fails
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
[342.137ms] [rows:1] UPDATE `users` SET `created_at`='2023-11-13 09:56:24.37',`updated_at`='2023-11-13 09:56:25.504',`deleted_at`=NULL,`name`='Joh
n' WHERE `users`.`deleted_at` IS NULL AND `id` = 1
```

**Comment by ouyuanning** [comment] 2023-11-13 13:17
i will have a look tomorrow

**Comment by ouyuanning** [comment] 2023-11-14 06:15
the root cause is:
when update the table with foreign key constraint in no action.
if parent table have any rows in that foreign key, MO will throw error.  But MySQL will check, if update row equal old row, do not throw error.
eg:
```
create table f1 (a int primary key);
create table c1(aa int primary key, bb int, CONSTRAINT `fk_bb` FOREIGN KEY (`bb`) REFERENCES `f1`(`a`));
insert into f1 values (1);
insert into c1 values (1,1);
update f1 set a=a;  //MO throw error.  but MySQL not
```

**Comment by ouyuanning** [comment] 2023-11-14 06:20
and we have another bug for gorm & MO：
because we do not have this meta table:  INFORMATION_SCHEMA.table_constraints
gorm do not known we have create table `user_languages` success with foreign key.
then gorm will alter table `user_languages` to add new constraint and success too. so user_languages will have double constraints for fk_user_languages_language & fk_user_languages_user.
this bug will same as https://github.com/matrixorigin/matrixone/issues/10172

**Comment by ouyuanning** [comment] 2023-11-15 08:01
fix bug: when the updated data does not change, there is no need to check the constraints.
you can run your test code succeed now.

but you will also get double constraints for `fk_user_languages_language` & `fk_user_languages_user` in table `user_languages`.  that will be fixed by @qingxinhome in future.

**Comment by dengn** [comment] 2023-11-16 02:18
fixed.

**Comment by dengn** [comment] 2023-11-16 07:09
@xuanyiLee please help close this issue.

**Closed** 2023-11-16 07:12 UTC
Labels: kind/bug, source/on-demand, team/c2
