### ISSUE TITLE
[Bug]: The performance of external tables is about 10 times worse than that of internal tables

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5450] opened 2022-10-08 07:10 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The data volume of the internal and external tables is 1000w. Compared with the performance of the three types of SQL, the difference is about 10 times:
![image](https://user-images.githubusercontent.com/113406637/194694843-a2dbc741-5506-488f-b7b2-f92daf40038e.png)

### Steps to Reproduce

```Markdown
create external table ex_table_1000w(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255))infile{"filepath"='/Users/heni/test_data/10000000_20_columns_load_data.csv'};
select count(*) from ex_table_1000w;--耗时9s
select count(distinct clo1) from ex_table_1000w;--耗时9s
select clo1,sum(clo2)  from ex_table_1000w group by clo1 having sum(clo2)>0 order by clo1;--耗时9s

create table table_1000w(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255));
insert into table_1000w select * from ex_table_1000w;--耗时1min3s
select count(*) from table_1000w;--耗时0.09s
select count(distinct clo1) from table_1000w;--耗时0.21s
select clo1,sum(clo2)  from table_1000w group by clo1 having sum(clo2)>0 order by clo1;--耗时0.9s
```

**Comment by fengttt** [comment] 2022-11-15 20:43
external table will always be slower.   However, need to track external table performance in general.

**Comment by daviszhen** [comment] 2022-11-21 14:34
we do not focus on it today

**Comment by fengttt** [comment] 2022-11-27 08:17
not a bug.   individual issues will be handled in different issues, please close this one

**Closed** 2022-12-01 10:46 UTC
Labels: kind/bug, triage/accepted, severity/s1
