### ISSUE TITLE
[Bug]: Invalid alloc size 1147486208 in tpch 100G with pessmistic txn mode

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#10682] opened 2023-07-15 06:57 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"FATAL","time":"2023/06/27 06:14:32.617620 +0000","caller":"mpool/mpool.go:521","msg":"Invalid alloc size 1147486208","stacktrace":"github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Alloc\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/mpool/mpool.go:521\ngithub.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Realloc\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/mpool/mpool.go:628\ngithub.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Grow\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/mpool/mpool.go:694\ngithub.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Grow2\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/mpool/mpool.go:707\ngithub.com/matrixorigin/matrixone/pkg/container/types.BuildVarlena\n\t/go/src/github.com/matrixorigin/matrixone/pkg/container/types/bytes.go:75\ngithub.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).UnionBatch\n\t/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/vector.go:2200\ngithub.com/matrixorigin/matrixone/pkg/container/batch.(*Batch).Append\n\t/go/src/github.com/matrixorigin/matrixone/pkg/container/batch/batch.go:305\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/hashbuild.(*container).build\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/hashbuild/build.go:127\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/hashbuild.Call\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/hashbuild/build.go:72\ngithub.com/matrixorigin/matrixone/pkg/vm.Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:61\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:152\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:146\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:117"}

**Comment by aunjgr** [comment] 2023-07-17 04:15
duplicate to #10707

**Comment by fengttt** [comment] 2023-07-17 04:35
reassign only after fix completed.   thank you.

**Comment by aunjgr** [comment] 2023-07-18 04:53
There's no caller to types.BuildVarlena in main branch for a while.

@zhangxu19830126 First of all please merge main.

**Comment by aunjgr** [comment] 2023-07-21 12:10
no reproduce

**Comment by aunjgr** [comment] 2023-07-24 11:30
can't reproduce

**Comment by aunjgr** [comment] 2023-07-26 05:08
degrade to s1 since no reproduce

**Closed** 2023-08-24 11:27 UTC
Labels: kind/bug, needs-triage, severity/s1
