### ISSUE TITLE
[Bug]: Unique not in effect

### ISSUE THREAD

**Issue by mklzl** [matrixorigin/matrixone#7045] opened 2022-12-04 05:08 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): c6d26e186a9b7e59282e3f846d448febec3ecf47
- Hardware parameters: 16G mem  . 50G disk
- OS type:centos 7.9
- Others:
```

### Actual Behavior

Unique  table not in effect

### Expected Behavior

unique is effective

### Steps to Reproduce

```Markdown
1. create unique table

CREATE TABLE `firstmodb`.`uniqueusers` (
  `id` bigint,
  `balance` decimal(15,2),
  `nickname` varchar(100) UNIQUE NOT NULL,
  PRIMARY KEY (`id`)
);

2. show create table 

 show create table firstmodb.uniqueusers;
```

### Additional information

mysql> show create table firstmodb.uniqueusers;;
+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| Table       | Create Table                                                                                                                                        |
+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| uniqueusers | CREATE TABLE `uniqueusers` (
`id` BIGINT DEFAULT NULL,
`balance` DECIMAL(15,2) DEFAULT NULL,
`nickname` VARCHAR(100) NOT NULL,
PRIMARY KEY (`id`)
) |
+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by sukki37** [comment] 2022-12-04 08:47
this bug will be fixed after finishing https://github.com/matrixorigin/matrixone/issues/4098.

**Comment by qingxinhome** [comment] 2022-12-14 13:07
still work on it

**Comment by qingxinhome** [comment] 2022-12-23 08:03
The execution result of the show create table statement should show the definition of the unique index in the table

**Comment by bbbearxyz** [comment] 2022-12-23 11:31
will solve it after unique index pr is merge

**Comment by bbbearxyz** [comment] 2022-12-30 07:04
the problem is solved, please test it.

**Closed** 2023-02-20 01:44 UTC
Labels: kind/bug, needs-triage, severity/s1
