### ISSUE TITLE
[Bug]: mo restart failed after killing the mo process directedly

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7362] opened 2022-12-28 14:31 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):12752c4b04771afe89d2e28d074166b2cfc74243
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo restart failed after killing the mo process directedly
error log:
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
        /data1/sudong/head/pkg/frontend/routine.go:165
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
        /data1/sudong/head/pkg/frontend/routine_manager.go:290
github.com/fagongzi/goetty/v2.(*server).doConnection
        /root/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
        /root/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
2022/12/28 21:05:19.350649 +0800 ERROR frontend/util.go:509 SQL parser error: table "sys_async_task" does not exist {"session_info": "connectionId 1602"}
github.com/matrixorigin/matrixone/pkg/frontend.logError
        /data1/sudong/head/pkg/frontend/util.go:509
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /data1/sudong/head/pkg/frontend/mysql_cmd_executor.go:3807
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /data1/sudong/head/pkg/frontend/mysql_cmd_executor.go:3930
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
        /data1/sudong/head/pkg/frontend/routine.go:165
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
        /data1/sudong/head/pkg/frontend/routine_manager.go:290
github.com/fagongzi/goetty/v2.(*server).doConnection
        /root/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
        /root/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
[server (3).log](https://github.com/matrixorigin/matrixone/files/10314692/server.3.log)

**Comment by volgariver6** [comment] 2023-01-03 02:24
Please @daviszhen help to check it. Timeout is caused by table not existing.

```
2022/12/28 21:05:19.350778 +0800 ERROR cn-service cnservice/server_task.go:163 wait all init task completed failed {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "Error 1064: SQL parser error: table \"sys_async_task\" does not exist"}
```

**Comment by daviszhen** [comment] 2023-01-03 13:32
I am not working on it.

**Comment by daviszhen** [comment] 2023-01-04 13:36
I am not working on it.

**Comment by daviszhen** [comment] 2023-01-06 15:21
I am not working on it.

**Comment by daviszhen** [comment] 2023-01-10 13:38
I am not working on it.

**Comment by daviszhen** [comment] 2023-01-12 13:40
I am not working on it.

**Comment by daviszhen** [comment] 2023-01-13 12:55
I am not working on it.

**Comment by daviszhen** [comment] 2023-01-16 03:24
it is closely related to the error.

```
7 results - 1 file

~/Downloads/server.3.log:
  7666  2022/12/28 21:00:39.451631 +0800 INFO tasks/job.go:99 run-job {"id": "load-cd751e16-47f5-4423-aaff-77c6f8eb2946:7074138_960_960:7075098_1344_1344:7076442_1088_1088:7077530_320_320:7077850_1344_1344:7079194_2240_2240:7081434_1600_1600:7083034_320_320:7083354_1600_1600:7084954_3136_3136:7088090_320_320:7088410_704_704:7089114_1344_1344:7090458_320_320:7090778_1344_1344:7092122_1216_1216:7093338_1728_1728:7095066_320_320:7095386_1728_1728:7097114_1216_1216:7098330_1728_1728:7100058_320_320:7100378_1728_1728:7102106_1216_1216", "duration": "42.322161ms"}
  7667: 2022/12/28 21:00:39.454687 +0800 ERROR frontend/util.go:509 open mo-data/s3/c0c08a1d-1972-4b96-a325-4428e96e4272: permission denied {"session_info": "connectionId 1009"}
  7668  github.com/matrixorigin/matrixone/pkg/frontend.logError

  7681  	/root/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
  7682: ⟪ 260 characters skipped ⟫, task_epoch, last_heartbeat, result_code, error_msg, create_at, end_at from mo_task.sys_async_task where task_status = 2 and task_metadata_executor = 1 order by task_id", "status": "fail", "error": "open mo-data/s3/c0c08a1d-1972-4b96-a325-4428e96e4272: permission denied", "span": {"trace_id": "a0d422a0-86af-11ed-8e3e-b07b25f8b524", "kind": "statement"}, "session_info": "connectionId 1009"}
  7683  github.com/matrixorigin/matrixone/pkg/frontend.logError

  7700  	/root/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
  7701: 2022/12/28 21:00:39.454949 +0800 ERROR cn-service cnservice/server_task.go:163 wait all init task completed failed {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "Error 1105: open mo-data/s3/c0c08a1d-1972-4b96-a325-4428e96e4272: permission denied"}
  7702  2022/12/28 21:00:39.474477 +0800 INFO tasks/job.go:99 run-job {"id": "fc33e490-b10b-4030-a406-e1a97fa41801", "duration": "29.943012ms"}

  7740  2022/12/28 21:00:39.478953 +0800 ERROR v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:345 handle session failed {"listen-addresses": "[0.0.0.0:6001]", "error": "internal error: there is no user b45b3f84-90c7-49a6-b24c-a86c2f96775a"}
  7741: 2022/12/28 21:00:39.548831 +0800 ERROR frontend/util.go:509 open mo-data/s3/4bb31887-f4d1-4a26-bd29-4bbf29ba1ca3: permission denied {"session_info": "connectionId 1007"}
  7742  github.com/matrixorigin/matrixone/pkg/frontend.logError

  7755  	/root/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
  7756: 2022/12/28 21:00:39.548919 +0800 ERROR frontend/util.go:509 query trace status {"connection_id": 1007, "statement": "execute __mo_stmt_id_1 using @__mo_stmt_var_0,@__mo_stmt_var_1,@__mo_stmt_var_2,@__mo_stmt_var_3,@__mo_stmt_var_4,@__mo_stmt_var_5,@__mo_stmt_var_6,@__mo_stmt_var_7,@__mo_stmt_var_8,@__mo_stmt_var_9,@__mo_stmt_var_10", "status": "fail", "error": "open mo-data/s3/4bb31887-f4d1-4a26-bd29-4bbf29ba1ca3: permission denied", "span": {"trace_id": "a0d46a49-86af-11ed-8e3e-b07b25f8b524", "kind": "statement"}, "session_info": "connectionId 1007"}
  7757  github.com/matrixorigin/matrixone/pkg/frontend.logError

  7774  	/root/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
  7775: 2022/12/28 21:00:39.549283 +0800 ERROR log-service task/task_scheduler.go:74 failed to create new tasks {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "Error 1105: open mo-data/s3/4bb31887-f4d1-4a26-bd29-4bbf29ba1ca3: permission denied"}
  7776  github.com/matrixorigin/matrixone/pkg/hakeeper/task.(*scheduler).Create

  7790  	/data1/sudong/head/pkg/common/stopper/stopper.go:259
  7791: 2022/12/28 21:00:39.549318 +0800 ERROR log-service logservice/service_bootstrap.go:84 failed to create init tasks {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "Error 1105: open mo-data/s3/4bb31887-f4d1-4a26-bd29-4bbf29ba1ca3: permission denied"}
  7792  2022/12/28 21:00:39.549307 +0800 ERROR log-service task/task_scheduler.go:108 failed to query tasks {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "status": "Created", "error": "context deadline exceeded"}

```

**Comment by daviszhen** [comment] 2023-01-16 03:25
> open mo-data/s3/c0c08a1d-1972-4b96-a325-4428e96e4272: permission denied

it is related to the error.

```
open mo-data/s3/c0c08a1d-1972-4b96-a325-4428e96e4272: permission denied
```

**Comment by daviszhen** [comment] 2023-01-16 09:10
@aressu1985 
Please provide some info.
1, booting config launch-tae-CN-tae-DN?
2, on mac or ubuntu ?
3, What is the kill method ? ctrl+c or kill -9

**Comment by aressu1985** [comment] 2023-01-16 09:11
> @aressu1985
> Please provide some info.
> 1, booting config launch-tae-CN-tae-DN?
    yes
> 2, on mac or ubuntu ?
   centos 8
> 3, What is the kill method ? ctrl+c or kill -9
   kill -9

**Comment by daviszhen** [comment] 2023-01-16 09:35
Again.
How long time does the mo-server run before kill it?

**Comment by daviszhen** [comment] 2023-01-16 11:37
After talking with @aressu1985 , the reason may be the mo-service started by a login user, then close it and started again by a different login user.

**Comment by daviszhen** [comment] 2023-01-17 13:38
test team is trying the bool the mo-server with different login user.

**Comment by daviszhen** [comment] 2023-01-19 11:37
I am  not working on it today.

**Closed** 2023-01-20 03:23 UTC
Labels: kind/bug, needs-triage, severity/s0
