### ISSUE TITLE
[Bug]: execute tpch sql,cause mo-service crash.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#6991] opened 2022-11-29 03:03 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):2ee36456d0eb86e6fb1261e20c121fbf4b429166
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

commit id: 2ee36456d0eb86e6fb1261e20c121fbf4b429166

<img width="671" alt="截屏2022-11-29 10 59 55" src="https://user-images.githubusercontent.com/39303074/204428051-8a33edba-4213-4e27-85e0-0ce947b82feb.png">

log info:
<img width="1359" alt="截屏2022-11-29 10 22 37" src="https://user-images.githubusercontent.com/39303074/204428070-99a7d02b-9aee-4d2c-9737-97876f838b76.png">

mo.log:
[mo-service.log.zip](https://github.com/matrixorigin/matrixone/files/10109360/mo-service.log.zip)

**Comment by jensenojs** [comment] 2022-12-05 12:24
i have tried locally with a little modification of the script, without this, load data will fail.
![image](https://user-images.githubusercontent.com/56761542/205636005-59505a67-0587-472b-b412-0b4672651d9b.png)

according to tianyahui 0.1G can reappearance this issue but i did't. Tomorrow I will check again on the remote machine to see if the problem can be repeated. I'm not sure if it's a script problem right now, if so, it can be solved in a day or two.

**Comment by jensenojs** [comment] 2022-12-06 07:14
let tianyahui reproduce this error

**Comment by tianyahui-python** [comment] 2022-12-14 10:17
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/3691276741/jobs/6252277210

**Comment by tianyahui-python** [comment] 2022-12-14 10:17
The bug appears again

**Comment by tianyahui-python** [comment] 2022-12-15 04:01
<img width="1396" alt="截屏2022-12-15 11 52 33" src="https://user-images.githubusercontent.com/39303074/207769158-bd7037bd-d762-4917-b16f-1b5617761e94.png">

**Comment by jensenojs** [comment] 2022-12-15 04:02
will fix later, Working on other bugs right now

**Comment by tianyahui-python** [comment] 2022-12-15 04:11
[mo-service.log](https://github.com/matrixorigin/matrixone/files/10233638/mo-service.log)

**Comment by jensenojs** [comment] 2022-12-16 05:46
working on it

**Comment by jensenojs** [comment] 2022-12-19 02:17
working on it

**Comment by jensenojs** [comment] 2022-12-19 12:09
Not reproducible locally, but stable on 128 machines (inconsistent error messages, related to memtable, memorytable), while it should not be a problem of the environment (at least not purely).

128 can still run tpch correctly in this commit https://github.com/matrixorigin/matrixone/commit/b662dd2edac50ceed22b8e91a67e5276eb8c6150

**Comment by jensenojs** [comment] 2022-12-20 08:47
A stable way to reproduce the problem (but is not so stable) is to redirect the logs to mo-logservice.log
```sh
./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml &>mo-service.log &
```
This approach triggers the panic a lot, so I use git bisect to find the first commit that triggers the problem is #7221 .

But by running tpch in the above way it may still pass,  so although I ran each commit three to five times during the binary lookup, I still can't guarantee that this is the earliest commit that triggered the problem.

![image](https://user-images.githubusercontent.com/56761542/208620203-12e84b99-b126-469b-a3aa-a9682b33ec90.png)

The next step is to investigate what this commit does

**Comment by jensenojs** [comment] 2022-12-20 09:05
It is common to repeat more than three times to reproduce the bug, If it does not reproduce successfully on #7221 , please give some patience and try a few more times.

link to tpch : https://github.com/matrixorigin/mo-tpch

**Comment by reusee** [comment] 2022-12-21 07:09
How can I reproduce this? How to run TPCH tests?

**Comment by jensenojs** [comment] 2022-12-21 07:11
refer to https://github.com/matrixorigin/mo-tpch

**Comment by jensenojs** [comment] 2022-12-21 07:20
[87a12107_failed.log](https://github.com/matrixorigin/matrixone/files/10275397/87a12107_failed.log)

**Comment by reusee** [comment] 2022-12-21 07:23
> [87a12107_failed.log](https://github.com/matrixorigin/matrixone/files/10275397/87a12107_failed.log)

It seems like a hardware error or compiler bug.

**Comment by sukki37** [comment] 2022-12-21 16:31
`a248ad7b`  many errors like 
```
runtime: marked free object in span 0x7f218c2dcd98, elemsize=96 freeindex=0 (bad use of unsafe.Pointer? try -d=checkptr)
0xc00af34000 free  unmarked
0xc00af34060 free  unmarked
0xc00af340c0 free  unmarked
0xc00af34120 free  unmarked
0xc00af34180 free  marked   zombie
0x000000c00af34180:  0x000000c009a9be60  0x0000000000000004
0x000000c00af34190:  0x000000c009a9be64  0x0000000000000003
0x000000c00af341a0:  0x000000c009a9be67  0x0000000000000004
0x000000c00af341b0:  0x000000c009a9be6b  0x0000000000000006
0x000000c00af341c0:  0x000000c009a9be71  0x000000000000007d
0x000000c00af341d0:  0x000000c009a9be60  0x0000000000000000
0xc00af341e0 free  unmarked
0xc00af34240 free  unmarked
0xc00af342a0 free  unmarked
0xc00af34300 free  unmarked
0xc00af34360 free  unmarked
0xc00af343c0 free  unmarked
0xc00af34420 free  unmarked
0xc00af34480 free  unmarked
0xc00af344e0 free  unmarked
0xc00af34540 free  unmarked
0xc00af345a0 free  unmarked
0xc00af34600 free  unmarked
```

**Comment by reusee** [comment] 2022-12-21 16:59
As indicated in the error message, I built the mo-service with the following:
```
go build -gcflags=all=-d=checkptr ./cmd/mo-service
```
And run the TPCH test:
```
./run.sh -g -s 1
./run.sh -l -s 1
./run.sh -q all -s 1
```
The test finished without error.

**Comment by reusee** [comment] 2022-12-21 17:46
bisecting from 061e71bf5109029d20bd8c475e09126d852d2985 to latest

**Comment by reusee** [comment] 2022-12-21 18:25
result
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
83d4ebf4717bbc2ec54a703f45fecca90ecf8cc6
2b376b671a2ba7e6ff69e87f1ad1b5442c821b18
fd8435be2ce67f1e6d33f15820e48f57e70babed
5448c8a182192b16b63e6e16f8139a3bc4daf2a8
```

**Comment by reusee** [comment] 2022-12-21 18:49
Confirmed, 061e71bf5109029d20bd8c475e09126d852d2985 is bad.
Hard to find a commit that passes TPCH.

**Comment by reusee** [comment] 2022-12-22 02:12
Retrying bisect.
This time I re-run the test even if it crashes for another reason. If it doesn't crash for memory corruption, it is a good commit.

**Comment by reusee** [comment] 2022-12-22 02:15
Memory corruption crashes all occurred in the query tests, never in a load test. So I guess the root cause is in the `sql` package

**Comment by fengttt** [comment] 2022-12-22 03:05
@reusee remember to file bugs from "crash of another reason".

**Comment by reusee** [comment] 2022-12-22 03:21
> @reusee remember to file bugs from "crash of another reason".

Those may be fixed in the following commits. If not, they will occur again.

**Comment by reusee** [comment] 2022-12-22 12:58
No luck in bisecting.
I'm going to check all usages of `unsafe` and remove some if possible.

**Comment by reusee** [comment] 2022-12-25 13:37
in progress

**Comment by reusee** [comment] 2022-12-26 12:09
in progress

**Comment by reusee** [comment] 2022-12-27 14:35
on sick leave.

**Comment by reusee** [comment] 2022-12-28 15:27
on sick leave.

**Comment by reusee** [comment] 2022-12-29 15:47
debugging

**Comment by reusee** [comment] 2022-12-30 04:31
No longer reproducible in the main branch, re-assign to @aressu1985

**Comment by aressu1985** [comment] 2023-01-03 07:07
this can be closed because it did not happened for 4 days

**Closed by aressu1985** 2023-01-03 07:07 UTC
Labels: kind/bug, severity/s-1
