### ISSUE TITLE
[Bug]: python udf: create or replace function reported Duplicate entry 'py_add' for key '__mo_index_idx_col'

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13898] opened 2023-12-28 08:34 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

a553f08d2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

same function name but not same column type  ,create or replace function failed:
<img width="1524" alt="企业微信截图_2a40dc7a-51d1-4834-aa8e-957de092691d" src="https://github.com/matrixorigin/matrixone/assets/113406637/facb09f0-f2e3-4421-ad6e-39d15fca9a7b">

### Steps to Reproduce

```Markdown
sql:
create or replace function py_add(a int, b bigint) returns int language python as  $$ def add(a, b):   return a + b $$ handler 'add';
create or replace function py_add(a int, b int) returns int language python as  $$ def add(a, b):   return a + b $$ handler 'add';
```

**Comment by aylei** [comment] 2023-12-28 09:47
not a bug

feature request: https://github.com/matrixorigin/matrixone/issues/13905

please kindly close this issue if the above FR would help

**Comment by heni02** [comment] 2023-12-29 07:22
confirm，closed

**Closed** 2023-12-29 07:23 UTC
Labels: kind/bug, severity/s0
