### ISSUE TITLE
[Bug]: Illegal Insert : When I insert an INTEGER value into TIMESTAMP, right?

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#5300] opened 2022-09-28 03:43 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The Structure is : 
CREATE TABLE t1(
    curr_dt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    id INT,
    PRIMARY KEY (curr_dt)
);
CREATE TABLE t2(
    curr_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    id INT,
    PRIMARY KEY (curr_ts)
);

The SQL statement is : 
INSERT INTO t2(curr_ts, id) VALUES(1, 1), (NOW(), 3);

The result is : 
+---------------------+------+
| curr_ts             | id   |
+---------------------+------+
| 2022-09-28 13:24:09 |    3 |
| 1970-01-01 10:00:01 |    1 |
+---------------------+------+

But the result on MySQL is : 
ERROR 1292 (22007): Incorrect datetime value: '1' for column 'curr_ts' at row 1

**Comment by goodMan-code** [comment] 2022-09-28 03:46
Another question is : If the value 1 of the integer type represents the second, why isn't the initial time of timestamp 1970-01-01 00:00:00? as we can see, the result is 1970-01-01 10:00:01

**Comment by aunjgr** [comment] 2022-10-29 16:30
According to discussions in version 0.5, our rule matrix of CAST should follow snowflake (https://docs.snowflake.com/en/sql-reference/data-type-conversion.html). So numeric types should be both castable(explicit) and coercible(implicit) to timestamp.

I can't reproduce the 10:00:01 result. On my machine, the result of `select cast(1 as timestamp);` is `1970-01-01 08:00:01`. Please check the value of your time_zone variable.

**Comment by fengttt** [comment] 2022-11-01 20:45
What is the conclusion?   Why do we close this issue without a decision?

**Comment by goodMan-code** [comment] 2022-11-02 02:24
> What is the conclusion? Why do we close this issue without a decision?

Dr. Tian, as @aunjgr say, numeric types should be both castable(explicit) and coercible(implicit) to timestamp，and I have Recheck on commit ccfcd648ea670d1bbb62c6cf8967e16fb7cc2a4d , It's result is correct.

**Comment by aressu1985** [comment] 2022-11-09 02:39
I will confirm this issue today

**Closed** 2022-11-28 02:16 UTC
Labels: kind/bug, triage/accepted, severity/s1
