### ISSUE TITLE
[Bug]: Mysql server gone away

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#1606] opened 2022-01-12 11:18 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a08aefcbf08fafde85d98ef10dbd26d588716cbe
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 create table t3 (isbn3 varchar(21) not null, libname3 varchar(21) not null, quantity int);create table t1 (libname1 varchar(21) not null primary key, city varchar(20));
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    1006
Current database: test

ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    1007
Current database: test

ERROR 2006 (HY000): MySQL server has gone away
ERROR 2006 (HY000): MySQL server has gone away

### Additional information

+++++++++
{"level":"ERROR","time":"2022/01/12 19:12:13.958765 +0800","caller":"logutil/api.go:63","msg":"routine send response failed &{1 0 3 0xc0000ef560 0 0 0}. error:illegal state ","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/github/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/root/github/matrixone/pkg/frontend/routine.go:105"}
+++++++++
:6 
+++++++++
{"level":"info","ts":"2022-01-12 19:12:14.809","logger":"goetty","caller":"goetty@v1.13.0/application.go:216","msg":"session connected","listen-address":"0.0.0.0:6001","session-id":4,"addr":"127.0.0.1:51836"}
+++++++++
:11 
+++++++++
{"level":"ERROR","time":"2022/01/12 19:12:14.812234 +0800","caller":"logutil/api.go:63","msg":"routine send response failed &{1 0 3 0xc008eba2d0 0 0 0}. error:write tcp4 127.0.0.1:6001->127.0.0.1:51836: write: broken pipe ","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/github/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/root/github/matrixone/pkg/frontend/routine.go:105"}
{"level":"info","ts":"2022-01-12 19:12:14.812","logger":"goetty","caller":"goetty@v1.13.0/application.go:216","msg":"session connected","listen-address":"0.0.0.0:6001","session-id":5,"addr":"127.0.0.1:51838"}
+++++++++
:11 
+++++++++
{"level":"ERROR","time":"2022/01/12 19:12:14.828147 +0800","caller":"logutil/api.go:63","msg":"routine send response failed &{1 0 3 0xc0000ef560 0 0 0}. error:illegal state ","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/github/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/root/github/matrixone/pkg/frontend/routine.go:105"}
{"level":"info","ts":"2022-01-12 19:12:32.115","logger":"goetty","caller":"goetty@v1.13.0/application.go:216","msg":"session connected","listen-address":"0.0.0.0:6001","session-id":6,"addr":"127.0.0.1:51858"}
+++++++++
:11 
+++++++++
{"level":"ERROR","time":"2022/01/12 19:12:32.118668 +0800","caller":"logutil/api.go:63","msg":"routine send response failed &{1 0 3 0xc0000ef560 0 0 0}. error:illegal state ","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/github/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/root/github/matrixone/pkg/frontend/routine.go:105"}
{"level":"info","ts":"2022-01-12 19:12:32.118","logger":"goetty","caller":"goetty@v1.13.0/application.go:216","msg":"session connected","listen-address":"0.0.0.0:6001","session-id":7,"addr":"127.0.0.1:51860"}
+++++++++
:11 
+++++++++
{"level":"info","ts":"2022-01-12 19:12:32.121","logger":"goetty","caller":"goetty@v1.13.0/application.go:216","msg":"session connected","listen-address":"0.0.0.0:6001","session-id":8,"addr":"127.0.0.1:51862"}
+++++++++
:11 
+++++++++
+++++++++
:12 
+++++++++
{"level":"info","ts":"2022-01-12 19:12:32.137","logger":"goetty","caller":"goetty@v1.13.0/application.go:216","msg":"session connected","listen-address":"0.0.0.0:6001","session-id":9,"addr":"127.0.0.1:51864"}
+++++++++
:11 
+++++++++
{"level":"ERROR","time":"2022/01/12 19:12:32.139415 +0800","caller":"logutil/api.go:63","msg":"routine send response failed &{1 0 4 0xc0000ef560 0 0 0}. error:illegal state ","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/github/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/root/github/matrixone/pkg/frontend/routine.go:105"}
+++++++++
:12 
+++++++++
+++++++++
:6 
+++++++++
+++++++++
:6 
+++++++++
{"level":"ERROR","time":"2022/01/12 19:12:32.158262 +0800","caller":"logutil/api.go:63","msg":"routine send response failed &{1 0 3 0xc0000ef560 0 0 0}. error:illegal state ","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/github/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/root/github/matrixone/pkg/frontend/routine.go:105"}

**Comment by daviszhen** [comment] 2022-01-13 02:08
I could not reproduce it on mac pro and ubuntu.

**Comment by JinHai-CN** [comment] 2022-02-28 02:53
can't reproduce, close it.

**Closed by JinHai-CN** 2022-02-28 02:53 UTC
Labels: kind/bug, needs-triage
