### ISSUE TITLE
[Bug]: there are some unexpected r-w confilict during tpcc logrunning test and insert-delete oltp test 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9348] opened 2023-05-09 12:34 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):65bdd570cb0580e82ef997e72c411ae7a1cd1b6c
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When run oltp insert-delte and tpcc long running test, there ares some unexpected r-w confilict error .

<img width="1421" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/ee0612f9-95d9-4bf5-a679-e2f5b02478c2">

<img width="645" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/f4f104e2-f845-419c-a4a8-ea3071b9f87f">

### Expected Behavior

this exception should not be ocurred.

**Comment by aressu1985** [comment] 2023-05-09 12:35
Has discussed with @XuPeng-SH , and he know the reason ,and do not need the mo log. pls assign this issue to @XuPeng-SH

**Comment by triump2020** [comment] 2023-05-12 13:37
blocked by other S-1 issue.

**Comment by triump2020** [comment] 2023-05-15 14:55
no progress

**Comment by triump2020** [comment] 2023-05-18 14:49
blocked by other s-1 bug

**Comment by triump2020** [comment] 2023-05-23 11:08
blocked by range/deletes optimization

**Comment by sukki37** [comment] 2023-05-24 14:12
repro in commit regression test:

https://github.com/matrixorigin/matrixone/actions/runs/5067549359/jobs/9098992700

https://github.com/matrixorigin/matrixone/actions/runs/5067981412/jobs/9100000169

**Comment by triump2020** [comment] 2023-05-29 11:37
no progress

**Comment by triump2020** [comment] 2023-06-05 05:14
reproduced, try to find the cause now.

**Comment by triump2020** [comment] 2023-06-10 13:42
in testing

**Comment by triump2020** [comment] 2023-06-10 13:54
@aressu1985  pls test.

**Comment by aressu1985** [comment] 2023-06-16 03:15
fixed

**Comment by aressu1985** [comment] 2023-06-19 04:11
this happen again on commit: 70cd870

<img width="1055" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/7813496b-9bd7-439c-9dcd-572e01543c6e">

log can be get from loki:
ns: mo-nightly-regression

**Comment by XuPeng-SH** [comment] 2023-06-20 00:57
It should be fixed by #10133

**Comment by aressu1985** [comment] 2023-06-20 03:44
this issue still exist
https://github.com/matrixorigin/matrixone/actions/runs/5317767539/jobs/9628685537

**Comment by sukki37** [comment] 2023-06-21 01:11
repro:https://github.com/matrixorigin/matrixone/actions/runs/5325558080/jobs/9648684647

**Comment by triump2020** [comment] 2023-06-25 14:02
blocked

**Comment by triump2020** [comment] 2023-07-04 15:11
no progress

**Comment by triump2020** [comment] 2023-07-07 14:38
no progress

**Comment by triump2020** [comment] 2023-07-13 10:35
on vacation

**Comment by triump2020** [comment] 2023-07-18 14:25
blocked

**Comment by triump2020** [comment] 2023-07-21 14:36
blocked

**Comment by triump2020** [comment] 2023-07-26 16:48
> All the reasons lead to rw conflcit are as follows: ![1688038754745](https://user-images.githubusercontent.com/63033222/249759890-05a06688-c402-4ca9-b350-60cc9382a86f.png)

@aressu1985 @XuPeng-SH   All the causes to RW conflicts are as above,   i think it's difficult to fix it complety in V1.0, but  fortunately it occurs with a low probability now.

**Comment by aressu1985** [comment] 2023-08-02 12:56
need to be discussed on next week meeting to confirm how to deal with this issue

**Comment by aressu1985** [comment] 2023-08-23 01:55
@XuPeng-SH pls reassign this issue

**Comment by XuPeng-SH** [comment] 2024-05-28 13:38
not repro any more

**Closed** 2024-07-18 02:06 UTC
Labels: kind/bug, severity/s1, phase/testing
