### ISSUE TITLE
[Bug]: Pessimistic on EKS test: cn crashed.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11124] opened 2023-08-09 07:31 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 52a8f95efda02e1d7411895a6b9cd8fb107f1523
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5803704691/job/15733524356
<img width="723" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c76fa549-78de-4b2e-96da-fbf1255d0807">
TPCH回归失败，从时间点上判断可能与pod重启无关，需要进一步定位：
<img width="1359" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/ecfd2dc2-a91a-4627-a69d-f7f5ec03d332">

log url: http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-rc%5C%22,%20pod%3D%5C%22nightly-regression-dis-rc-tp-cn-2nbrk%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D

<img width="1345" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/cc95aaf8-12b8-4962-b99a-3b002d97eb54">

**Comment by zhangxu19830126** [comment] 2023-08-09 13:20
tpch failed on  Pessimistic

**Comment by badboynt1** [comment] 2023-08-10 03:21
caused by this pr: https://github.com/matrixorigin/matrixone/pull/11090

**Comment by badboynt1** [comment] 2023-08-10 03:58
will be fixed in this pr: https://github.com/matrixorigin/matrixone/pull/11138
verified on eks: https://github.com/matrixorigin/mo-auto-test/actions/runs/5816590997/job/15770071870

**Comment by badboynt1** [comment] 2023-08-10 06:20
fixed

**Comment by Ariznawlll** [comment] 2023-08-11 05:52
Verified in：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5823409982

**Closed** 2023-08-11 05:55 UTC
Labels: kind/bug, needs-triage, severity/s-1
