### ISSUE TITLE
[Bug]: sysbench mixed test report strange error.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#13738] opened 2023-12-22 09:58 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.0-dev

### Commit ID

8081e0516065caf2531835c42f92e00c99f0082a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1646" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/da316203-44ee-40de-912c-ddad640d47e0">
<img width="1038" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/cb304414-61a4-4bd8-8d1b-0b4c401eb1fd">
<img width="1647" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a20c8655-dbc9-4187-b56d-43375fd9520e">

sysbench工具log：
[sysbench.log](https://github.com/matrixorigin/matrixone/files/13751114/sysbench.log)

mo-log：http://10.222.6.1/explore?panes=%7B%22uUC%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
混合场景并行跑
```

**Comment by daviszhen** [comment] 2023-12-25 11:29
截图上是utc+8的时间。实际是utc 21号。

**Comment by daviszhen** [comment] 2023-12-26 03:58
sysbench.log 有几种报错情况：
1，the connection between CN and TN has been disconnected
发生时间点在utc 2023-12-21 19:43:00 左右。
这个原因未明确，大概率是cn重启了。但是在监控上看不出来此时间点有pod重启。

发生在utc 2023-12-21 20:40:00 前后。cn重启。能在监控上看到。http://10.222.6.1/d/cluster-detail-namespaced/cluster-detail-namespaced?orgId=1&from=1703181600000&to=1703203199000&var-namespace=mo-stability-regression&var-account=All&var-interval=$__auto_interval_interval&var-cluster=.%2A&var-loki=loki



2，Communications link failure. 
lock table not found on remote lock service 
 Could not create connection to database server. 
dial tcp4 10.10.4.99:6003: connect: connection refused
Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
发生在 utc 2023-12-21 20:20:00 前后。
以及utc 2023-12-21 20:40:00 前后。
以及utc 2023-12-21 21:48:00 前后。

这段时间是cn oom重启导致的。监控的时间点能对得上。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/859f6bb5-f0be-4e55-bbce-a8816b60d0bf)

http://10.222.6.1/d/cluster-detail-namespaced/cluster-detail-namespaced?orgId=1&from=1703181600000&to=1703203199000&var-namespace=mo-stability-regression&var-account=All&var-interval=$__auto_interval_interval&var-cluster=.%2A&var-loki=loki

**Comment by daviszhen** [comment] 2023-12-26 04:00
就utc 2023-12-21 19:43:00 这个时间点 时间点日志与监控。其它时间点日志与监控基本对得上

**Comment by ouyuanning** [comment] 2023-12-26 05:14
只处理OOM部分

**Comment by nnsgmsone** [comment] 2024-01-25 10:16
no process

**Comment by nnsgmsone** [comment] 2024-01-30 10:20
no process

**Comment by nnsgmsone** [comment] 2024-02-02 10:15
no process

**Comment by nnsgmsone** [comment] 2024-02-21 13:45
no process

**Comment by nnsgmsone** [comment] 2024-02-26 10:22
no process

**Comment by nnsgmsone** [comment] 2024-03-05 10:18
no process

**Comment by nnsgmsone** [comment] 2024-03-08 10:36
no proess

**Comment by nnsgmsone** [comment] 2024-03-13 10:17
no process

**Comment by nnsgmsone** [comment] 2024-03-18 11:01
no process

**Comment by nnsgmsone** [comment] 2024-03-21 10:13
no process

**Comment by sukki37** [comment] 2024-03-26 09:28
The issue is outdated, and neither the context nor the environment has been preserved, making it impossible to locate. Close it for now. If it reoccurs, open a new issue.

**Closed by sukki37** 2024-03-26 09:28 UTC
Labels: kind/bug, severity/s0, team/c2, impact/1.0
