### ISSUE TITLE
[Bug]: mistake with the purge_log query result

### ISSUE THREAD

**Issue by lacrimosaprinz** [matrixorigin/matrixone#10421] opened 2023-07-05 05:22 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select date(collecttime), count(1) from system_metrics.metric group by date(collecttime);
+-------------------+----------+
| date(collecttime) | count(1) |
+-------------------+----------+
| 2023-07-04        |    74991 |
| 2023-07-03        |    38608 |
| 2023-07-05        |      378 |
+-------------------+----------+
3 rows in set (0.04 sec)

mysql> select purge_log('rawlog,statement_info,metric', '2023-07-04');
+-----------------------------------------------------+
| purge_log(rawlog,statement_info,metric, 2023-07-04) |
+-----------------------------------------------------+
|                                                   0 |
+-----------------------------------------------------+
1 row in set (0.03 sec)

mysql> select date(collecttime), count(1) from system_metrics.metric group by date(collecttime);
+-------------------+----------+
| date(collecttime) | count(1) |
+-------------------+----------+
| 2023-07-04        |    74991 |
| 2023-07-03        |    38608 |
| 2023-07-05        |      598 |
+-------------------+----------+
3 rows in set (0.01 sec)

**Comment by xzxiong** [comment] 2023-07-05 09:21
root cause: purge_log 在执行删除时，仅处理了 第一个表的结果就返回了。

**Comment by xzxiong** [comment] 2023-07-07 03:15
@lacrimosaprinz ptal, bugfix has been merged

**Closed** 2023-07-07 03:19 UTC
Labels: kind/bug, needs-triage, severity/s0
