### ISSUE TITLE
[Bug]: [date 1.11] tke regression: establish a connection takes 3 minutes

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14165] opened 2024-01-12 08:34 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

dd90efb5a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7490212917/job/20400077309
<img width="1427" alt="企业微信截图_c90e3df1-8aa1-491a-be2a-7f3ec3e89dcb" src="https://github.com/matrixorigin/matrixone/assets/113406637/18ec00ed-2b13-4c41-9dac-6f4eea85dba0">

mo log：
http://175.178.192.213:30088/explore?panes=%7B%22qYx%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240111%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221705005180000%22,%22to%22:%221705005720000%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="2092" alt="企业微信截图_4e2150f4-14f1-49e7-9892-87d1230c6612" src="https://github.com/matrixorigin/matrixone/assets/113406637/c3c269ae-a158-488b-bbd5-11dadfb56a7e">

### Steps to Reproduce

```Markdown
tke regression
```

**Comment by heni02** [comment] 2024-01-12 08:35
@LeftHandCold 辛苦将定位信息贴一下

**Comment by LeftHandCold** [comment] 2024-01-12 09:11
发现当时的cn只打印一些定时任务的log，和频繁打印goroutine，查看goroutine的metrics，发现当时数量比较多，不知道是否正常。
<img width="543" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/131e58bd-9772-4b84-91db-44ecefdf5516">

**Comment by LeftHandCold** [comment] 2024-01-12 09:12
http://175.178.192.213:30088/d/e3623bad-403a-41f2-956e-21196de1f2ec/go-runtime-metrics?orgId=1&from=now-12h&to=now&var-interval=1m&var-namespace=mo-nightly-regression-20240111&var-pod=All

**Comment by XuPeng-SH** [comment] 2024-01-15 02:05
@zhangxu19830126 please take a look at this issue

**Comment by zhangxu19830126** [comment] 2024-01-15 07:13
maybe fixed by #14176. Too many socket connections maybe cause this problem

**Comment by zhangxu19830126** [comment] 2024-01-15 07:23
But the log means, txn leak happened, please take a look @daviszhen

**Comment by daviszhen** [comment] 2024-01-19 10:16
未投入

**Comment by daviszhen** [comment] 2024-01-24 12:14
未投入

**Comment by daviszhen** [comment] 2024-02-02 11:51
未投入

**Comment by daviszhen** [comment] 2024-02-07 10:14
未投入

**Comment by daviszhen** [comment] 2024-02-21 13:13
未投入

**Comment by daviszhen** [comment] 2024-02-26 12:42
未投入

**Comment by daviszhen** [comment] 2024-03-05 13:36
未投入

**Comment by daviszhen** [comment] 2024-03-08 10:43
未投入

**Comment by daviszhen** [comment] 2024-03-18 11:38
未投入

**Comment by daviszhen** [comment] 2024-03-21 10:57
未投入

**Comment by daviszhen** [comment] 2024-03-26 12:54
未投入

**Comment by daviszhen** [comment] 2024-03-29 12:36
未投入

**Comment by daviszhen** [comment] 2024-04-03 10:41
未投入

**Comment by daviszhen** [comment] 2024-04-08 11:05
未投入

**Comment by daviszhen** [comment] 2024-04-11 13:55
未投入

**Comment by daviszhen** [comment] 2024-04-16 11:36
未投入

**Comment by daviszhen** [comment] 2024-04-19 13:54
未投入

**Comment by daviszhen** [comment] 2024-04-24 11:44
未投入

**Comment by daviszhen** [comment] 2024-04-30 10:15
未投入

**Comment by daviszhen** [comment] 2024-05-05 12:34
未投入

**Comment by daviszhen** [comment] 2024-05-09 10:45
未投入

**Comment by daviszhen** [comment] 2024-05-14 12:59
未投入

**Comment by daviszhen** [comment] 2024-05-22 12:15
未投入

**Comment by daviszhen** [comment] 2024-05-27 12:44
未投入

**Comment by daviszhen** [comment] 2024-05-30 11:12
未投入

**Comment by daviszhen** [comment] 2024-06-12 12:03
未投入

**Comment by daviszhen** [comment] 2024-06-17 11:05
未投入

**Comment by daviszhen** [comment] 2024-06-20 13:26
未投入

**Comment by daviszhen** [comment] 2024-06-25 11:06
未投入

**Comment by daviszhen** [comment] 2024-06-28 10:53
未投入

**Comment by sukki37** [comment] 2024-07-02 16:28
Closing this issue due to inactivity. Feel free to reopen or create a new issue if needed. Thanks!

**Closed by sukki37** 2024-07-02 16:28 UTC
Labels: kind/bug, severity/s0
