### ISSUE TITLE
[Bug]: a simple query : mo be suspended by local Machine, and killed by local System 2 min later

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#6694] opened 2022-11-16 04:24 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

launch parameters : 
commit 873bc541f9ccb4fbb948688a6f6d91ce2c6939c7
launch method : ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml > mo.log 2>&1 &
mysql -h 127.0.0.1 -P 6001 -udump -p111

The problem is : 
When I execute a simple query, mo return no any response, and killed by 2 min later forced by local Machine ( Ubuntu I used )
as you can see this picture, memory used 72% even more, local memory 32G. mo not panic, and the log has no panic info.
![2022-11-16 12-19-22屏幕截图](https://user-images.githubusercontent.com/74952516/202082617-c91dfe95-0772-4e63-b1eb-7a430302e261.png)

Execute Step:
1. launch MO
2. create database test;
3. use test;
4. 
```sql
CREATE TABLE `system_menu` (
  `id` int(10) unsigned NOT NULL,
  `parent_id` int(11) NOT NULL COMMENT '父级id',
  `title` varchar(64)  NOT NULL COMMENT '中文名称',
  `title_en` varchar(64)  NOT NULL COMMENT '英文名称',
  `icon` varchar(64)  DEFAULT '' COMMENT '坐标',
  `root` varchar(255)  NOT NULL COMMENT '根路径',
  `path` varchar(255)  NOT NULL COMMENT '路由路径',
  `order` tinyint(4) NOT NULL DEFAULT '0' COMMENT '排序：升序',
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `hide_in_menu` tinyint(3) NOT NULL DEFAULT '0' COMMENT '是否隐藏 0否 1是',
  `location` tinyint(3) NOT NULL DEFAULT '0' COMMENT 'location：0：左边，1：左下，2：左上，3：上边，4：右上',
  PRIMARY KEY (`id`)
) COMMENT='系统菜单表';
```
5. 
```sql
SELECT
id,parent_id,title,title_en,icon,root,path,`order`,created_at,updated_at,hide_in_menu,location 
FROM
system_menu
WHERE
(id IN ('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','26','27','28','29') AND hide_in_menu = 0) ORDER BY `id` ASC;
```
6. use " top " to watch some indicator.

**Comment by aunjgr** [comment] 2022-11-16 07:32
[cpu.prof.gz](https://github.com/matrixorigin/matrixone/files/10019096/cpu.prof.gz)

I tested EXPLAIN of above query, and it's still extremely slow (11.5 seconds per run). Profile shows the choke point is plan.checkDNF.

@badboynt1 Please have a look.

**Comment by aunjgr** [comment] 2022-11-16 08:21
oom only occurs on tae-CN-DN. Can't reproduce on tae-logservice. It is caused by computeRangeByIntPk

@ouyuanning

**Comment by aunjgr** [comment] 2022-11-16 10:53
The plan issue has been fixed by #6709 and #6712

**Comment by ouyuanning** [comment] 2022-11-16 11:04
working on fix problem in computeRangeByIntPk.

**Comment by goodMan-code** [comment] 2022-11-17 03:12
Recheck on 2022-11-17 11:12 AM GMT+8, it has been fixed, can be closed. done.

**Closed** 2022-11-17 03:12 UTC
Labels: kind/bug, needs-triage, severity/s0
